Netflix/metaflow

metaflow/tutorials/03-playlist-redux/playlist.py, metaflow/tutorials/04-playlist-plus/playlist.py
Couple of typos fixed and cleaned unused imports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netflix/metaflow/36)
=> Fix minor typo/import fixes in 03-playlist-redux tutorial.

metaflow/main_cli.py
Fix Unbound error from unassigned var.
=> Fix typo in cli

setup.py
Release notes -
1. Handle Keyboard interrupts for Batch jobs more gracefully
2. Revamp the `metaflow configure aws` command to address usability
issues
3. Introduce `metaflow configure [import|export]` to share configurations
4. Fix docker registry parsing logic to handle namespace better
5. Fix typos in tutorials
=> Bump metaflow version to 2.0.1 in preparation for release

.github/workflows/publish.yml, .github/workflows/test.yml
https://github.com/actions/checkout/releases
=> Upgrade GitHub actions/checkout@v1 --> v2

metaflow/datatools/s3.py
Fixes GH-84
Trap and fail immediately instead of retrying.
=> Trap "NoSuchBucket" errors

metaflow/graph.py
=> Maintain indentation for the 'show' command

metaflow/parameters.py
=> replace hyphen with under score in parameter

metaflow/cli.py, metaflow/current.py, metaflow/task.py
current.retry_count now returns the retry attempt (0, 1, .. so on)
for a metaflow task
=> Expose Retry Count in Current Singleton

metaflow/cli.py, metaflow/datastore/datastore.py, metaflow/environment.py, metaflow/graph.py, metaflow/main_cli.py, metaflow/metaflow_config.py, metaflow/parameters.py, metaflow/plugins/__init__.py, metaflow/plugins/aws/batch/batch.py, metaflow/plugins/aws/batch/batch_cli.py, metaflow/plugins/aws/batch/batch_client.py, metaflow/plugins/aws/batch/batch_decorator.py, metaflow/plugins/aws/step_functions/dynamo_db_client.py, metaflow/plugins/aws/step_functions/event_bridge_client.py, metaflow/plugins/aws/step_functions/production_token.py, metaflow/plugins/aws/step_functions/set_batch_environment.py, metaflow/plugins/aws/step_functions/step_functions.py, metaflow/plugins/aws/step_functions/step_functions_cli.py, metaflow/plugins/aws/step_functions/step_functions_client.py, metaflow/plugins/aws/step_functions/step_functions_decorator.py, metaflow/plugins/schedule_decorator.py, metaflow/util.py
Integrates Metaflow with [AWS Step Functions](https://aws.amazon.com/step-functions/).
Introduces a new command `step-functions`:
- `python my_flow.py step-functions create` will compile and export the user-defined Metaflow flow into an AWS Step Functions state machine. This will allow users of Metaflow to move their flows into production seamlessly with AWS. 
- An additional flow level decorator, `@schedule`, allows users to optionally schedule the execution of their flows by integrating with AWS Event Bridge. 
- All current functionality of Metaflow - containerized job execution on top of AWS Batch through `@batch`, dependency management via `@conda`, retrying mechanisms through `@retry`, `@catch` and `@timeout`, parameters, branches, and for-eaches are now available within AWS Step …
=> AWS Step Functions Integration

metaflow/plugins/aws/batch/batch_client.py
CloudWatchLogStream might not be immediately created (and may never
be created if say the job fails to pull the docker image for any reason
whatsoever). We can simply retry again next time.
=> Handle CloudWatchLogs resource creation delay gracefully

metaflow/cli.py
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
=> Remove unused import

metaflow/package.py
Package `.RDS` files in the code package for @batch execution of R flows.
=> Package .RDS files for @batch

setup.py
Introduce hooks for R bindings
=> Bump Metaflow minor version to 2.2.0

metaflow/datastore/datastore_set.py, metaflow/main_cli.py
Execution barfs with Python 3.5 otherwise
=> Cast bytes to unicode object for json.loads

R/README.md
with installation instructions and user guide.
=> Update README for R package

metaflow/plugins/conda/conda_environment.py
=> Conda environment now returns the information from the default environment

metaflow/debug.py
=> Properly handle strings passed to debug

metaflow/exception.py, metaflow/flowspec.py, test/core/tests/merge_artifacts_include.py
Supersedes #237 (changed merge order and targeting master).
=> Add 'include' parameter to merge_artifacts for easier control of artifacts to merge

metaflow/metadata/service.py
I am perplexed how did it work correctly previously!
=> Correctly invoke class method for 409 retries

metaflow/debug.py
=> Fix import in Debug

R/inst/run_batch.R
add digest pkg dependency to batch setup for R
=> add digest pkg dependency to batch setup for R

metaflow/graph.py
this avoids importing the flow module and execution of any user-defined code
=> AST-only version of graph.FlowGraph

setup.py
Update version number from 2.2.2 to 2.2.3
=> update version number to 2.2.3

metaflow/graph.py
=> Revert "AST-only version of graph.FlowGraph"

R/R/step.R
=> Fix small typo

R/R/flags.R, R/R/flow.R, R/R/run.R, R/tests/testthat/test-flow.R, R/tests/testthat/test-run-cmd.R, R/tests/testthat/test-run.R, R/tests/testthat/test-sfn-cli-parsing.R, R/tests/testthat/test-step.R, metaflow/R.py, metaflow/plugins/aws/step_functions/step_functions.py
Add step functions support for Metaflow R binding.
=> step function integration for R binding

.github/workflows/publish.yml, .github/workflows/test.yml, R/tests/run_tests.R
=> update ci test.yml

setup.py
This release contains the following patches 
#364 
#349
#346 
#343 
#342 
#332 
#331 
#330
#321
=> Upgrade patch version to 2.2.4 for release

metaflow/datastore/local.py, metaflow/datastore/s3.py, metaflow/metadata/metadata.py, metaflow/plugins/aws/batch/batch_decorator.py, metaflow/plugins/aws/step_functions/step_functions_decorator.py, metaflow/plugins/conda/conda_step_decorator.py, metaflow/runtime.py, metaflow/task.py
write attempt status at the end of every task attempt
=> allow tagging of metadata and add attempt status to metadata table

metaflow/includefile.py, metaflow/parameters.py, metaflow/plugins/aws/step_functions/step_functions_cli.py
IncludeFile now delays uploading/saving the file until *after* the flow
has been validated and PyLint has run (if needed).
=> Delay IncludeFile evaluation

metaflow/plugins/aws/step_functions/step_functions_cli.py
Reverts Netflix/metaflow#409
Context - https://gitter.im/metaflow_org/community?at=602c049647585464db8137e3
=> Revert "Support step-functions --with ... cli format"

metaflow/client/core.py
=> Fix bug with legacy log loads

metaflow/metadata/heartbeat.py
Fixes a bug with parsing the response of Metaflow heartbeat
=> Fix bug with Metaflow heartbeats

metaflow/plugins/aws/step_functions/step_functions_cli.py
This will allow easy override of state machine names in AWS Step Functions - `python flow.py step-functions --name foo create`
=> Add `--name` argument for step-functions operations

metaflow/plugins/aws/step_functions/step_functions_cli.py
AWS Step Functions only allows for `[^a-zA-Z0-9_\-\.]` in the state machine
name. Given that now users can override the state machine name with any
arbitrary name, it is important to validate the name of the state machine
before pushing the workflow to AWS Step Functions
=> Validate `--name` for AWS Step Functions commands

metaflow/cli.py, metaflow/client/core.py, metaflow/client/filecache.py, metaflow/datastore/datastore_set.py, metaflow/datastore/flow_datastore.py, metaflow/datastore/task_datastore.py, metaflow/datastore/util/s3tail.py, metaflow/metaflow_environment.py, metaflow/mflog/__init__.py, metaflow/mflog/mflog.py, metaflow/mflog/save_logs.py, metaflow/mflog/save_logs_periodically.py, metaflow/mflog/tee.py, metaflow/plugins/__init__.py, metaflow/plugins/aws/batch/batch.py, metaflow/plugins/aws/batch/batch_cli.py, metaflow/plugins/aws/batch/batch_client.py, metaflow/plugins/aws/batch/batch_decorator.py, metaflow/plugins/aws/step_functions/step_functions.py, metaflow/plugins/conda/conda_environment.py, metaflow/runtime.py, metaflow/task.py, test/core/metaflow_test/cli_check.py, test/core/metaflow_test/formatter.py, test/core/metaflow_test/mli_check.py, test/core/run_tests.py, test/core/tests/detect_segfault.py, test/core/tests/large_mflog.py
This is still in progress but pushing for reference.
=> MFLog on convergence branch

metaflow/plugins/aws/step_functions/step_functions_cli.py
Similar to the existing `run --run-id-file`
=> Add --run-id-file option to step-functions trigger

metaflow/client/filecache.py, metaflow/datastore/content_addressed_store.py, metaflow/datastore/datastore_backend.py, metaflow/datastore/datastore_set.py, metaflow/datastore/flow_datastore.py, metaflow/datastore/local_backend.py, metaflow/datastore/s3_backend.py, metaflow/datastore/task_datastore.py
- remove artifact_cache
- simplify blob_cache (esp. in DatastoreSet)
- remove LazyFile
- small stylistic changes
=> Simplify new datastore [not tested thoroughly]

metaflow/__init__.py
When you override an existing module inside a metaflow custom
package, we now create a module suffixed with '_orig' (so, for
example, if you override 'metaflow.plugins.aws', you can access
the original module as 'metaflow.plugins.aws._orig'
=> Create a shadowed module when overriding in metaflow_custom

metaflow/flowspec.py
=> Handle parameters as `foreach vars`

metaflow/plugins/conda/conda_environment.py
=> Conda environment now applys underlying environment's decorators

metaflow/plugins/conda/conda_environment.py
=> Fixes recursion error when METAFLOW_DEFAULT_ENVIRONMENT=conda

R/inst/tutorials/04-helloaws/helloaws.Rmd, R/inst/tutorials/05-statistics-redux/README.md, R/inst/tutorials/07-autopilot/README.md, docs/Environment escape.md, docs/concurrency.md, metaflow/datastore/datastore.py, metaflow/datastore/local.py, metaflow/datastore/s3.py, metaflow/flowspec.py, metaflow/lint.py, metaflow/main_cli.py, metaflow/metaflow_environment.py, metaflow/metaflow_version.py, metaflow/plugins/aws/batch/batch_decorator.py, metaflow/plugins/aws/step_functions/step_functions.py, metaflow/plugins/conda/conda.py, metaflow/plugins/env_escape/client.py, metaflow/plugins/env_escape/override_decorators.py, metaflow/plugins/env_escape/server.py, metaflow/plugins/env_escape/stub.py, metaflow/plugins/metadata/local.py, metaflow/sidecar.py, metaflow/tutorials/05-helloaws/helloaws.ipynb, test/data/s3/test_s3.py
[`codespell --ignore-words-list="ans,ba,doesnt" --skip="*.csv,*.html"](https://pypi.org/project/codespell)
=> Fix typos discovered by codespell

metaflow/util.py
```
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
--builtins=assert_equals,assert_exception,inputs,is_resumed,NUM_FOREACH,NUM_LINES,ResumeFromHere,TestRetry
./metaflow/metaflow/util.py:36:13: F821 undefined name 'self'
self.path = path
^
```
=> Don't forget "self" in class methods

test/core/tests/param_names.py
=> Added test for parameter names.

.github/workflows/publish.yml, .github/workflows/test.yml
Temporary removal of R tests to unblock Metaflow release while we investigate what's causing the issue.
=> Mute R tests

.github/workflows/test.yml, metaflow/client/core.py
Because making it work for forked repos is a pain at the moment.
=> Remove auto-formatter for black

metaflow/mflog/__init__.py, metaflow/plugins/aws/batch/batch.py, metaflow/plugins/aws/eks/kubernetes.py
=> Fix mflog capture for multiple commands

metaflow/mflog/__init__.py, metaflow/mflog/redirect_streams.py, metaflow/plugins/aws/batch/batch.py, metaflow/plugins/aws/eks/kubernetes.py
Ready for review - general housekeeping for #463
=> mflog changes for supporting AWS Lambda

metaflow/datatools/s3op.py, metaflow/datatools/s3tail.py, metaflow/mflog/__init__.py
=> Fix a couple of typos/issues in s3 error handling

metaflow/plugins/catch_decorator.py
only set ubf_control_tasks when in the parallel context
cc @oavdeev
=> fix @catch decorator for parallel

metaflow/tutorials/04-playlist-plus/playlist.py
Hi, I found a couple of small formatting typos in the tutorial.
=> Fix small typos in tutorial 04-playlist-plus/playlist.py

metaflow/cli.py, metaflow/datastore/__init__.py
Fix https://github.com/Netflix/metaflow/issues/816
=> fixed cli command when task_id provided

metaflow/plugins/aws/aws_utils.py, metaflow/plugins/aws/batch/batch_decorator.py, metaflow/plugins/aws/eks/kubernetes_decorator.py, metaflow/plugins/aws/step_functions/step_functions.py
=> Fix default resource math 

setup.py
Version bump PR Post merging #893
=> Version Bump 

metaflow/cards.py, metaflow/plugins/cards/card_decorator.py
1. API Surface cleanup 
2. Removing some unnecessary codebits
=> Removing some code bits from `metaflow.cards`

metaflow/metaflow_config.py, metaflow/plugins/conda/conda.py
Builds on top of work by @jimgoo
=> Introduce Mamba as a dependency solver for `@conda`

metaflow/package.py
- files pointed by symlinks are now dereferenced by tar (no symlinks inside tar)
- symlink cycles are detected
- if no symlinks are present, the package should be identical to the previous versions
=> follow symlinks in packaging

metaflow/plugins/conda/conda.py
=> Fix "Too many symbolic links" error when using Conda + Batch on MacOS

metaflow/plugins/aws/batch/batch.py
=> Emit app tag for AWS Batch jobs

metaflow/extension_support.py, metaflow/plugins/__init__.py, metaflow/plugins/cards/card_decorator.py, metaflow/plugins/cards/card_modules/__init__.py
- tiny bug fix to extensions.
- Added card related refactor to support mfextinit and regular package.
- removing card packaging related code in decorator
=> Moving card import changes on top of Romain's branch

metaflow/extension_support.py, metaflow/plugins/cards/card_cli.py, metaflow/plugins/cards/card_decorator.py, metaflow/plugins/cards/card_modules/components.py, metaflow/plugins/cards/component_serializer.py, metaflow/plugins/cards/exception.py, test/core/tests/card_extension_test.py, test/core/tests/card_timeout.py
Cherry-picking changes from : 
- Changes from #986
- https://github.com/Netflix/metaflow/commit/ed7169095eae1102ce278d756f0593c19556a88f
=> Card Nits + Extension Test fix + Options fix

metaflow/datatools/s3.py
=> Skip sleep if not retryting S3 operations

.github/workflows/test.yml, .pre-commit-config.yaml, metaflow/client/core.py, metaflow/client/filecache.py, metaflow/plugins/cards/card_modules/chevron/renderer.py, metaflow/plugins/env_escape/data_transferer.py, metaflow/task.py, test/core/metaflow_test/__init__.py, test/core/metaflow_test/formatter.py, test/core/tests/resume_end_step.py, test/core/tests/resume_start_step.py
This adds it on the client side
=> Alternate way of adding metadata to cloned tasks

metaflow/plugins/cards/card_modules/convert_to_native_type.py
=> Card dataframe bug Fix

metaflow/event_logger.py
Pushing directly per our conversation with Savin
=> Small typo in NullEventLogger.send

metaflow/datatools/s3util.py
Fix for the failing test https://github.com/Netflix/metaflow/blob/master/test/core/tests/s3_failure.py reported by @oavdeev
=> Fixed s3util test

metaflow/plugins/airflow/airflow.py, metaflow/plugins/airflow/airflow_cli.py
This PR Simplifies how parameters are parsed. It also moves around the code that raises errors during dag compilation to raising errors before DAG compilation (if there are any).
=> Simplifying Airflow parameter creation

metaflow/includefile.py, metaflow/plugins/azure/includefile_support.py
=> Add back Azure support

metaflow/client/core.py, metaflow/datastore/task_datastore.py, metaflow/datatools/__init__.py, metaflow/datatools/local.py, metaflow/flowspec.py, metaflow/includefile.py, metaflow/parameters.py, metaflow/plugins/airflow/airflow.py, metaflow/plugins/airflow/airflow_cli.py, metaflow/plugins/argo/argo_workflows_cli.py, metaflow/plugins/aws/step_functions/step_functions_cli.py, metaflow/plugins/azure/includefile_support.py, test/core/metaflow_test/cli_check.py, test/core/metaflow_test/metadata_check.py, test/core/tests/basic_include.py
This rewrite addresses several issues:
- IncludeFile were not properly returned in dump and via the client
- Improves logic in create/trigger for step-functions for example
- Properly consider the size of the included file when dumping
artifacts
- default value for IncludeFile can also now be a function
The code has been cleaned up overall as well and many more comments
added.
=> Rewrite IncludeFile implementation

metaflow/plugins/cards/card_modules/components.py
pandas imported as pd, so pandas.DataFrame will fail
=> fix pandas call bug

metaflow/plugins/airflow/airflow.py, metaflow/plugins/airflow/airflow_utils.py
These changes add Metaflow Pathspec to the Airflow UI.
=> Metaflow pathspec in Airflow UI

.github/workflows/test.yml
=> Check compatibility for R 4.2

metaflow/plugins/kubernetes/kubernetes.py
Log the message and the exit code.
=> Handle aborted Kubernetes workloads.

setup.py, tox.ini
Update version for immediate release
=> Fix regression causing CL tool to not work.

metaflow/cmd/tutorials_cmd.py
=> Adds check for tutorials dir and flattens if necessary

metaflow/client/core.py, metaflow/metadata/util.py, metaflow/util.py
=> Fix CVE-2007-4559 (tar.extractall)

metaflow/plugins/argo/argo_workflows.py
Drive-by.... make the program self modifying (`_cron = _cron()`)
=> Fix timezone code in Argo Workflows

metaflow/plugins/env_escape/client.py
The escape hatch's mechanism to communicate with the "escaped" python process is not thread safe. This addresses this issue by properly locking when communicating with the backend process.
A more long term fix may be to also multithread the backend process and properly multiplex communication but it is unclear what the actual benefit would be as this mechanism is more frequently used in a single threaded manner.
=> Fix an issue with threading and the escape hatch.

metaflow/plugins/aws/batch/batch.py, metaflow/plugins/aws/batch/batch_client.py, metaflow/plugins/aws/batch/batch_decorator.py
fixes to review comments for #1287
=> fix: review comments for tmpfs

metaflow/client/core.py
- add implementation comment and TODO to `run.code`
=> chore: comment on run.code 

metaflow/client/core.py, metaflow/events.py, metaflow/plugins/events_decorator.py
=> fix: event triggering docs

setup.py
- remove pylint as a hard dependency
=> feature: remove pylint dependency

metaflow/plugins/argo/argo_client.py, metaflow/plugins/argo/argo_workflows.py
refactor sensor deletion so it is easier to implement in #1307
=> feat: refactor sensor deletion

metaflow/monitor.py
added a return statement to one of the methods in the guage class.
=> added missing return statement

metaflow/plugins/aws/batch/batch_decorator.py
- add handling of missing metadata to batch decorator
addresses #1346
=> fix: batch decorator missing metadata handling

metaflow/current.py, test/core/tests/current_singleton.py
Update documentation to make it more accurate.
=> Update current object adding `run` and `task` object.

metaflow/plugins/aws/aws_utils.py, metaflow/plugins/aws/batch/batch.py, metaflow/plugins/aws/batch/batch_client.py
add sanitization for batch tags so they are guaranteed to adhere to AWS requirements.
addresses #1345
=> feature: add sanitization for batch tags

metaflow/plugins/events_decorator.py
Additional options to have explicit parameter mappings as well as a more flexible way of specifying project and branch
=> Add additional options to @trigger and @trigger_on_finish

metaflow/plugins/env_escape/exception_transferer.py
The issue would occur if an exception was both listed as a class and an exception in the mapping file.
=> Fix issue with handling of exceptions in the escape hatch

metaflow/plugins/argo/argo_workflows.py, metaflow/plugins/argo/argo_workflows_cli.py
Adds support for PagerDuty notifications for Argo Workflows.
=> feature: add PagerDuty support for Argo Workflows

metaflow/metaflow_config.py, metaflow/plugins/argo/argo_workflows.py, metaflow/plugins/kubernetes/kubernetes.py, metaflow/plugins/kubernetes/kubernetes_cli.py, metaflow/plugins/kubernetes/kubernetes_decorator.py, test/unit/test_kubernetes.py
=> Revert "Adds custom annotations via env variables"

metaflow/plugins/pypi/conda_decorator.py
adds support for legacy `@conda(libraries=)`
=> chore: support libraries attribute in new conda deco

metaflow/plugins/pypi/micromamba.py, metaflow/plugins/pypi/utils.py
fixes micromamba binary detection and adds a download step for the platform if micromamba is not installed.
=> chore: fix micromamba detection

metaflow/plugins/pypi/conda_environment.py, metaflow/plugins/pypi/micromamba.py
fixes issue with supplying multiple channels via `--channel` breaking for `--channel=conda-forge,defaults`
=> chore: fix microconda channels

metaflow/plugins/kubernetes/kubernetes_decorator.py
=> Revert "fix: GPU scheduling issue"

metaflow/plugins/argo/argo_client.py, metaflow/plugins/argo/argo_workflows.py, metaflow/plugins/argo/argo_workflows_cli.py
cleanup for the list-templates filter logic
=> chore: cleanup filter logic for argo

metaflow/plugins/pypi/bootstrap.py
cleanup debug print from pypi bootstrap
=> chore: cleanup pypi bootstrap

.gitignore, stubs/MANIFEST.in, stubs/setup.py
This is required for generating a conda package
=> fix stubs version check

metaflow/plugins/aws/batch/batch_decorator.py
adds an alias `trainium` for Batch decorators `inferentia` attribute
=> feature: add alias for batch decorator inferentia 

metaflow/version.py
Should be merged after https://github.com/Netflix/metaflow/pull/1779
=> Bump version to 2.11.7

metaflow/plugins/argo/argo_workflows_decorator.py
adds metadata for tracking Argo Workflows template owner
=> feature: add metadata for argo workflows template owner

metaflow/plugins/argo/argo_workflows.py
fixes issue where a partial event payload would not correctly use default values for a flow's Parameters.
=> fix: support default parameter values with argo events

metaflow/plugins/env_escape/__init__.py, metaflow/version.py
The flag added in PR 1819 is not imported correctly. Fix in this PR
=> fix import of the new escape hatch flag

metaflow/plugins/pypi/pip.py
add better errors for pypi package resolving failures
=> feature: polish pypi package errors

metaflow/plugins/argo/argo_workflows.py
fix using parameter names with dashes through Argo Events
=> fix: support for dashed parameters through argo events

metaflow/plugins/argo/argo_workflows.py, metaflow/plugins/kubernetes/kubernetes_job.py, metaflow/plugins/kubernetes/kubernetes_jobsets.py
- add a terminationMessagePolicy to FallbackToLogsOnError
=> [argo/k8s] add terminationMessagePolicy 

metaflow/plugins/argo/argo_workflows.py, metaflow/plugins/argo/capture_error.py
Fixes the error capture commands such that:
* we assign the error to an object
* we also export the error  to a env var
=> Fix error capture commands

metaflow/metaflow_config_funcs.py
fixes issue with metaflow local config initialization
=> fix: Metaflow local config init

metaflow/runtime.py
Pure window dressing PR to introduce consistency in logging messages
=> Align cloning log msgs

metaflow/plugins/pypi/conda_decorator.py
used in extensions when pulling attributes from a decorator instance, in order to determine if the deco has been specified by the user, or if it is untouched
=> feature: add is_attribute_user_defined check to conda decorators

metaflow/plugins/argo/argo_workflows.py
Fixes https://github.com/Netflix/metaflow/issues/2060
The diff is a bit ugly after running `black`; the real diff is just adding these:
```py
def service_account_name(self, service_account_name):
self.payload["serviceAccountName"] = service_account_name
return self
...
DaemonTemplate("heartbeat-daemon")
.service_account_name(resources["service_account"])
...
```
The alternative to this fix is to set `serviceAccountName` on WorkflowSpec. See this TODO [here](https://github.com/Netflix/metaflow/blob/cbfaea9e469093f06eaeeada04919ca0f71170f5/metaflow/plugins/argo/argo_workflows.py#L735). I chose to set this on DaemonTemplate instead to minimize the scope of this bugfix, but if adding to WorkflowSpec will be straightforward I can do that.
I've verified this by running
```
pip install …
```
=> Add serviceAccountName to DaemonTemplate

metaflow/plugins/pypi/micromamba.py
missed a commit from previous PR on Conda errors. Adds more detailed instructions for user on virtual package related errors
=> chore: more detailed instructions for conda errors

metaflow/plugins/argo/argo_client.py
adds specific exceptions for 404/403 cases to the argo client so these can be explicitly handled in `argo-workflows delete` for example
=> feature: add specific exceptions to argo client

.github/workflows/test.yml, setup.py
=> drop py3.5 / add py3.13

metaflow/plugins/cards/card_server.py
Fixes https://github.com/Netflix/metaflow/issues/2120
=> use METAFLOW_CARD_LOCALROOT for card server

metaflow/plugins/kubernetes/kubernetes_jobsets.py
The way we kill jobsets is by first doing a best effort kill of the control pod and if that doesn't work then we just go delete the jobset.
=> [jobsets] Fix killing jobsets

metaflow/plugins/pypi/bootstrap.py
cut down on env bootstrap latencies significantly
=> boost remote env bootstrap by 70%

metaflow/runtime.py
In some cases, when resuming a node with a foreach and resuming just at the join node, multiple instances of the join node could be created.
This PR addresses this issue.
=> Fix an issue with resume and foreach

metaflow/flowspec.py
Flow decorators are now properly merged when inheriting from other base flow specs.
=> Support flow inheritance specifically around flow decorators.

metaflow/runner/click_api.py
Fixes https://github.com/Netflix/metaflow/issues/2229
=> fix runner API for flowspec as super class

metaflow/metaflow_config.py, metaflow/plugins/pypi/bootstrap.py
Reverts Netflix/metaflow#2254 uggh.. didn't mean to merge
=> Revert "change default micromamba for s3 datastore"

.cursorrules, metaflow/metaflow_environment.py
saves roughly a second - a tiny way to save the planet
=> skip boto3 compilation for code download

.cursorrules, metaflow/plugins/metadata_providers/service.py
quick change to shave a second off of time taken to launch first task.
=> Introduce connection pooling in metadata service

metaflow/metaflow_config.py, metaflow/plugins/pypi/bootstrap.py
=> change default micromamba for s3 datastore

.github/workflows/test-stubs.yml
=> mute stubs test for linux py3.13

metaflow/runner/subprocess_manager.py
Relevant issue: https://github.com/Netflix/metaflow/issues/2291
=> skip signal handling in non main thread

metaflow/metaflow_environment.py, metaflow/mflog/__init__.py, metaflow/plugins/pypi/conda_environment.py
log lines (the first few) should now appear a lot more quicker on the terminal
=> more realtime log fetching

metaflow/plugins/argo/argo_workflows.py
add `source_url` to incident.io alert payload.
cleanup description in payload
=> chore: incident.io alert payload cleanup

metaflow/cli_components/run_cmds.py, metaflow/metaflow_version.py
effectively dead code that needs to be yanked out at some point
=> fix invalid imports

metaflow/plugins/pypi/conda_environment.py
Fixes some exceptions not being raised to the top when resolving conda/pypi environments. The cause being runaway threadpool futures that are submitted, but their results are never checked.
Changes so that all submitted futures in the threadpoolexecutor are accounted for and their results properly checked.
also adds `as_completed` to the pypi resolve futures, which might fix some edge cases with pypi resolving.
--- 
easiest way to test is with GCP datastore and the following edits:
`conda_environment.py#cache`
```python
storage.save_bytes(
list_of_path_and_filehandle,
len_hint=len(list_of_path_and_filehandle),
overwrite=True,
)
```
in order to force the upload of dependencies even if they exist
`gs_storage.py#save_bytes_single`
```python
blob.upload_from_filename(
tmpfile, …
```
=> fix: threaded resolve for conda/pypi omitting exceptions

metaflow/plugins/argo/argo_workflows_deployer_objects.py
json.loads does not work with {}. It needs to be `'{}'` .
=> fix default dict for json loads

metaflow/cmd/develop/stubs.py
=> Revert "update imports for py 3.7"

metaflow/plugins/metadata_providers/service.py, metaflow/plugins/pypi/bootstrap.py
Add retry to compute_info in Metadata service
=> Add retry to compute_info in Metadata service

metaflow/plugins/cards/card_datastore.py
Earlier the `save_card` function ended up saving cards at two locations. Thereby doubling the number of cards. (this was a temporary fix; which we never ended up getting rolled back) 
> Why did we do this ? :
When cards were introduced there was an assumption made about task-ids being unique. This assumption was incorrect. Only the pathspec is unique and there are no such guarantees about task-ids. When task-ids are non-unique, card read would result in finding incorrect cards (because cards were stored based on task-ids). If we had immediately switched from storing cards based on `task-ids` to a `step-name/task-id`, then card reading would have crashed for many users. It would especially happen for users who are accessing cards created by a newer MF client from an older version of MF …
=> [cards] remove dual write

metaflow/_vendor/imghdr.LICENSE, metaflow/_vendor/imghdr/__init__.py, metaflow/plugins/__init__.py, metaflow/plugins/cards/card_modules/convert_to_native_type.py, metaflow/plugins/cards/card_modules/test_cards.py
=> vendor imghdr into metaflow

metaflow/runner/metaflow_runner.py
When injecting commands to the runner, the stubs generated were not accurate or complete. This addresses this issue
=> Fixup how commands show up as part of the Runner API

metaflow/cmd/develop/stub_generator.py
=> Revert "[stubs] support for TypedDicts"

metaflow/plugins/secrets/__init__.py, metaflow/plugins/secrets/secrets_func.py
Changes the secret fetching function to a more comfortable UX:
```python
from metaflow.plugins.secrets import get_secret
secret_dict = get_secret(source="some-secret-source")
```
=> fix: change get_secrets to get_secret

metaflow/plugins/argo/argo_workflows.py
increases resource request for argo exit hook pods
=> feature: increase argo exit hook resources

metaflow/plugins/argo/argo_workflows.py
Argo workflows does not support applying imagePullSecrets on a per-template basis, only on a workflow template level. 
Changing the implementation to leverage podSpecPatch in order to apply the imagePullSecrets on a per task basis
JobSets were not tested but should be unaffected due to them utilizing `create` within the spec and simply dumping native k8s job specs
closes #2477
=> fix: kubernetes imagePullSecrets support for argo workflows

metaflow/_vendor/imghdr/__init__.py
Remove deprecation warning that resulted in runtime errors.
=> [cards] remove imghdr warnings

metaflow/cli.py
usage - `echo_always(line, wrap=True)`
=> add wrapping to echo

metaflow/plugins/argo/argo_workflows.py
adds support for recursive conditionals on argo workflows
=> feature: support recursive conditionals on Argo Workflows

metaflow/metadata_provider/metadata.py
Fixes missing git info metadata on remotely executing flows.
=> fix: missing git info on remote flows

devtools/Tiltfile, devtools/pick_services.sh
- Added Jobsets to the Mix
- Also added capability to lock versions for argo helm charts and images
=> [metaflow dev] Jobsets + Locking Versions

metaflow/parameters.py, metaflow/runner/click_api.py
fixes https://github.com/Netflix/metaflow/issues/2619
=> fix params leakage in click api
