metaflow/main_cli.py

The CLI incorrectly sets the environment config value of `METADATA_SERVICE_URL` during AWS config setup. This requires the user to manually set the value of `METAFLOW_SERVICE_URL` in it's place.
Fix for issue 43:
https://github.com/Netflix/metaflow/issues/43

Issue 43 - change environment variable name to correct key

---

metaflow/decorators.py
metaflow/plugins/conda/conda_step_decorator.py

Decorators can be specified for Metaflow steps via CLI. Some of the
decorator args can include commas, which break the current logic.
For eg, `--with conda:'libraries="{a:x.y,b:x.y}"',python=x.y.z`
This patch fixes the behavior by updating the parsing logic for decospec.

Better decorator parsing on CLI

---

metaflow/plugins/aws/batch/batch_decorator.py

re.search instead of re.match to disambiguate between valid docker
registry urls

Fix docker registry parsing for AWS Batch decorator

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_client.py
metaflow/runtime.py

Although not fully guaranteeing a clean shutdown every time, this patch makes the shutdown a little more robust (giving time to children process to shutdown), prevents multiple CTRL-C from interrupting the shutdown (in most cases) and is possibly faster in the presence of large fan outs.

Address #54 and improve interrupted shutdown

---

metaflow/flowspec.py

Conditional branching is not a supported feature in Metaflow yet. 
Remove the docstring from `def next` in FlowSpec.

Remove docstring for conditional in self.next

---

metaflow/plugins/conda/conda_step_decorator.py
setup.py

Looks like conda doesn't reliably/correctly update the `env/conda-meta/<package>.json` file which Metaflow relies on to identify which packages should be moved to S3 and their installation order on AWS Batch.
In this specific scenario, when the compute needs to execute on AWS Batch, Metaflow coaxes conda to generate an environment for `linux-64` architectures using only `.tar.bz2` dependencies, irrespective of where conda is executed from (usually a user's macOS or linux instance). In some very specific scenarios, conda correctly picks up the `.tar.bz2` dependencies from upstream repos but fails to update the manifest, incorrectly pointing to `.conda` dependencies instead. This leads to incorrect bundling of packages and the user job fails when executing on AWS Batch since we end up …

Add check on conda-package metadata to guard against .conda packages

---

metaflow/datastore/datastore.py
metaflow/plugins/conda/conda_step_decorator.py

Importing ABC from collections module will raise `ImportError` in Python 3.9 and raises `DeprecationWarning` from 3.4 . Hence use `collections.abc` and also preserve compatibility with Python 2. Ref : https://github.com/python/cpython/pull/10596

Use collections.abc for ABC import to fix Python 3.9 compatibility.

---

setup.py

1. Pin click to v7.0 or greater (#107)
2. Add checks to conda-package metadata to guard against .conda packages (#118)

Bump metaflow version to 2.0.2 in preparation for release

---

metaflow/plugins/conda/batch_bootstrap.py

Conda recently started shipping a stand-alone installer.
It is smaller than the current binary that we pull in (~10mb vs ~60mb)
as well as saves time since we don't have to install conda by itself.
As a follow-up, we can even dump the installer in the user's S3 bucket
to save this network ingress on AWS Batch.
Addresses #122

Switch to standalone conda installer on AWS Batch

---

metaflow/cli.py
metaflow/datastore/datastore.py

Gitter thread - https://gitter.im/metaflow_org/community?at=5e4b8e24d56ddb68a4aff877
Metaflow initializes datastore_root to fetch user code in `step` command. The behaviour defaults to relying on METAFLOW_DATASTORE_SYSROOT_S3 environment variable to initialize datastore_root. This patch checks if --datastore_root cli arg can be used instead.

Initialize datastore_root from cli args in cli.step(...)

---

metaflow/plugins/aws/batch/batch.py

There is an issue in syncing metadata for local metadata provider when using AWS Batch. 
I am using a local metadata provider with executes on Batch with S3 datastore. I was able to complete the flow successfully on batch and was trying to analyze results in a notebook. But when I access properties of the run like `run.data` it throws an error.
I am using https://github.com/valayDave/mnist-experiments-with-metaflow/blob/without_conda_test/hello_mnist.py as the file and running the following command :`python hello_mnist.py --with batch:cpu=2,memory=4000,image=tensorflow/tensorflow:latest-py3 run --num_training_examples 1000`. 
The odd thing is that there are two `.metaflow/.metaflow` folders in my directory and both of them holding the same flows and runs. When moved the data under …

Fixing directory issue of local metadataprovider with aws batch.

---

metaflow/environment.py

Purely a cosmetic change in AWS Batch job execution logs
Running with local metadata service pollutes the job logs with the statement `Creating local datastore in current directory (/metaflow/.metaflow)`.

Mute datastore creation log on AWS Batch for local metadata store

---

metaflow/current.py
metaflow/flowspec.py
metaflow/pylint_wrapper.py
metaflow/task.py

Addresses #137 .
You can now do:
for name in self.parameters:
print('I have a parameter %s with a value of %s' % (name, getattr(self, name)))

Add a method to list the name of the parameters for a flow.

---

setup.py

1. Use a smaller standalone Conda installer for AWS Batch
2. Add METAFLOW_S3_ENDPOINT_URL configuration (#130)
3. Use the CLI datastore-root before checking for METAFLOW_DATASTORE_SYSROOT_S3
4. Fix an issue where using the local metadata provider with Batch resulted
in .metaflow/.metaflow instead of just .metaflow
5. Add a way to get parameter names passed to a flow (using
current.parameter_names) (#137)
6. Properly indent on show (#92)
7. Surpress superfluous message when running on Batch

Release notes -

---

metaflow/datastore/util/s3util.py
metaflow/datatools/s3.py
metaflow/datatools/s3op.py
metaflow/metaflow_config.py

#130 
I fixed `endpoint_url` and replaced every `s3 = get_authenticated_boto3_client('s3')` call with `get_s3_client()`, because we should have only one entrypoint.
Not sure about the default `s3.amazonaws.com` url.
Tested. It works fine.

fix: endpoint_url for boto3 client

---

metaflow/plugins/conda/conda_step_decorator.py

In some edge cases, `python -s` doesn't explicitly set PYTHONNOUSERSITE.
More context - https://gitter.im/metaflow_org/community?at=5e8ee8315d148a0460f51623

Add PYTHONNOUSERSITE explicitly

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/batch/batch_client.py

`describeJobs` API for AWS Batch has particularly low concurrency limits. This PR adds throttling and jitter to the calls we make to aid in higher resiliency.

Set thresholds for retrying `describeJobs` in AWS Batch integration

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_client.py

Fix a bug where log collection gets into an infinite loop when AWS Batch job crashes before being executed on ECS. Clean up some log statements as well.

Pre-empt log collection when Batch task crashes

---

metaflow/plugins/aws/batch/batch_client.py

StepFunctions cannot control the retrying strategy for AWS Batch since `$$.State.RetryCount` in SFN ContextObject is a number and AWS Batch only accepts strings as configuration values.
So, instead of relying on StepFunctions to retry failed jobs, we will pass on the baton to AWS Batch instead.

Expose job attempt configuration for AWS Batch jobs

---

metaflow/plugins/aws/batch/batch_client.py

Currently, the flow logs are polluted with  occasional `ThrottleExceptions`.
They don't result in flow failures since we retry log fetching till the tasks
are alive and do a best-effort pull after the tasks have finished. This patch
swallows the `ThrottleExceptions` so that the end-user isn't thrown off track.
resolves #184

Mute `ThrottleException` for AWS Logs API for AWS Batch

---

metaflow/datatools/s3.py

When `datatools.S3._read_many_files` is unsuccessful, instead of displaying the underlying error message, we get a `TypeError: 'map' object is not subscriptable` due to trying to access the first element of `prefixes` with `[0]`. The `prefixes` passed in is a generator (map) which doesn't support this sort of access. The simplest fix is ~to remove the attempted logging of the _first prefix_~ to assign to a list inside the function. 
Better to report the underlying error correctly than a mysterious `'map' object is not subscriptable`. In my case I had an issue with a version of the [typing](https://pypi.org/project/typing/) library being incompatible with a version of [`certifi`](https://pypi.org/project/certifi/) which became obvious once the underlying error message was not being hidden. …

Fix logging of prefixes in datatools.S3._read_many_files

---

metaflow/plugins/aws/batch/batch_client.py

Modify the retry behavior for log fetching on AWS Batch by adding
jitters to exponential backoffs as well as reset the retry counter
for every successful request.
Additionally, fail the metaflow task even if AWS Batch task succeeds
but we fail to stream the task logs back to the user's terminal.

Increase retry count for AWS Batch logs streaming

---

setup.py

Tested locally by running `pip3 install .` in the repo folder. It can automatically downgrades pylint from `2.5.0` to `2.4.4`.

pin pylint version to 2.4.4 since 2.5.0 does not like self.next() syntax

---

.github/workflows/publish.yml

`created` event is not emitted when a draft release is published, while `published` event is always emitted with or without a draft release.

Trigger release on `published`

---

test/core/tests/large_artifact.py

Reduce file size from 4g to 2g. We will bump it back up when we get to custom runners for tests.

Verify that GitHub CI tests are failing due to large artifacts

---

metaflow/tutorials/05-helloaws/helloaws.ipynb
metaflow/tutorials/06-statistics-redux/stats.ipynb
metaflow/tutorials/07-worldview/worldview.ipynb

Setting namespace to None. A common scenario is where the user
copies to contents of the notebook into a sagemaker notebook and executes
the code snippets. That would fail, because the sagemaker notebook runs
with user:ec2-user. Setting the namespace to None allows us to bypass this
issue and provide a better user experience.

Set namespace to None in example notebook

---

metaflow/client/core.py

This removes the millisecond information from `created_at` and `finished_at` because `%f` directive is not compatible with `time`.
Fixes #224

Remove millisecond information from run timestamps

---

metaflow/environment.py

In some situations, the user might be left wondering where
exactly the code package is being fetched from, when such fetches
fail, making it harder to debug.
Closes #232

Throw a pretty error when metaflow fails to fetch the code package

---

metaflow/runtime.py

Logs might have leading whitespaces which are currently being removed from the user-visible logs on console.
Addresses #223

Handle log indenting in metaflow

---

metaflow/tutorials/04-playlist-plus/README.md
metaflow/tutorials/05-helloaws/README.md
metaflow/tutorials/06-statistics-redux/README.md
metaflow/tutorials/07-worldview/README.md

Some users might not have access to pandas within the docker container
executing their AWS Batch job. The situation is different for sandbox
accounts since the image bundles in pandas by default.
Added a command line flag to enable conda and pandas for all executions

Add instructions to tutorial 6 for execution inside a conda environment

---

metaflow/metadata/service.py

With AWS Step Functions, the metaflow task runtime registers
the step metadata, which is racy. This PR addresses that by properly
handling the 409 response from the metaflow service.

Handle 409s from /step endpoint in Metaflow Service

---

metaflow/plugins/aws/batch/batch_client.py

When IAM perms are incorrectly assigned, AWS Batch will be unable to
generate an AWS CloudWatch log stream. In those instances, we should
short circuit and return the actual error message.

Exit early if no log_stream is generated for AWS Batch job

---

metaflow/main_cli.py

It can confuse users. https://gitter.im/metaflow_org/community?at=5f298c7f0ff358499bd448a9

Remove https:// for dockerhub address in comment

---

.github/workflows/publish.yml
.github/workflows/test.yml
R/R/utils.R
R/tests/test_tutorials.sh

Update Metaflow R install function. Fix a problem with the argument name. 
Remove cran check from github action. CRAN check requires a proper setup of pdflatex, which is sometimes flaky on ubuntu:latest image.

update metaflow R install function. remove cran check from github action

---

metaflow/cli.py
metaflow/datatools/s3.py

Patching import of `current` to point to the singleton object rather than the python module

Fix imports in datatools.s3

---

metaflow/plugins/conda/conda.py

The conda_prefix folder is not always writable, so creating a lock there can fail.
On the other hand, conda's first entry in "envs_dirs" should always be writable.
Fix #179

Use the first environments directory instead of conda_prefix

---

metaflow/datastore/util/s3tail.py
metaflow/includefile.py
metaflow/package.py
metaflow/runtime.py
metaflow/util.py

This change only affects Python2; Python3 was already using BytesIO
Supersedes #272

Move from cStringIO.StringIO to BytesIO for more consistency.

---

metaflow/datastore/s3.py
metaflow/datatools/s3.py
test/core/tests/s3_failure.py

Uploads were not retried correctly since the buffer status was
not reset after the first attempt which led to an "IO on closed file"
error or an empty file being written to S3
Supersedes #234

Fix s3_put_object retries in datastore/s3.py. Also fail gracefully if boto3 is not installed

---

metaflow/plugins/conda/conda_environment.py

This reverts commit 1c0f4bd03581ea57e6b994ff382e59901f49d139.
The commit was initially dependent on another commit which has not yet been merged. We will re-push this commit once the other commit has also been merged.

Revert "Conda environment now returns the information from the default environment (#291)"

---

metaflow/plugins/conda/conda_step_decorator.py

add conda bin path to PATH environment variable so that we can use binaries installed by conda directly in the steps.

add conda bin path to PATH env variable

---

metaflow/metaflow_config.py
metaflow/plugins/conda/conda_step_decorator.py

Pin default libs version in conda environment based on different python versions. 
Supported python version: 2.7.x, 3.5.x, 3.6.x, 3.7.x, and 3.8.x

pin conda libs version depending on different python version

---

R/DESCRIPTION
R/R/step.R
R/tests/testthat/test-step.R

Addresses issue #313.
Version 0.6.19 (2019-05-20) of the `digest` package was the earliest to support the `spookyhash` algorithm.

Set minimum version of digest dependency to 0.6.19

---

R/R/flags.R
R/R/run.R

Fixing a bug where we treated `--authorize` as an option without argument and failed to parse the token argument.

fixing a bug for parsing --authorize in R SFN

---

metaflow/plugins/aws/step_functions/dynamo_db_client.py

Replace the `curl` function call with requests in case `curl` does not exist in a custom image.

fix an issue with aws region check in dynamodb client

---

metaflow/includefile.py
test/core/metaflow_test/__init__.py
test/core/metaflow_test/cli_check.py
test/core/metaflow_test/formatter.py
test/core/metaflow_test/mli_check.py
test/core/tests/basic_include.py

In some cases, overriding the default IncludeFile value would cause a crash.
This fixes this issue and adds tests to test this condition

Fix issue with IncludeFile caused in 2.1.0

---

metaflow/metaflow_config.py

This PR addresses #372 and modifies the Metaflow environment variable config to allow users to prefix Step Function state machines outside of the Metaflow AWS sandbox. It adds a new environment variable `METAFLOW_SFN_STATE_MACHINE_PREFIX` that controls this behavior but does not modify existing behavior when running in the Metaflow AWS sandbox.

Allow users to prefix SFN state machines outside Metaflow sandbox.

---

metaflow/plugins/conda/conda.py
metaflow/plugins/conda/conda_step_decorator.py

Conda fails to correctly set up environments for linux-64 packages on macOS which
is needed to collect the necessary metadata for correctly setting up the conda
environment on AWS Batch. This patch simply ignores the error-checks that conda
throws while setting up the environments on macOS when the intended destination
is AWS Batch.

Guard against inconsistently cased filesystems for @conda on macOS with @batch

---

metaflow/plugins/aws/step_functions/step_functions.py

Very wide workflows - `split-and` might cause issues with
AWS Step Functions because of the limitation imposed on step
name size. Changing the step name for a `Parallel` task type
in AWS Step Functions to a hashed value buys us a lot of
flexibility. This is not a user-visible change since the Parallel
step is an implementation detail of the Metaflow -> SFN compilation
process

Support very wide workflows in AWS Step Functions

---

metaflow/metaflow_config.py
metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/batch/batch_client.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/aws/step_functions/step_functions.py

Introduces support for executing AWS Batch tasks on top of AWS Fargate
compute platform.
1. Add a new environment variable - METAFLOW_ECS_FARGATE_EXECUTION_ROLE
to track ecsTaskExecutionRole for the Batch container and Fargate agent.
Can also be specified by the `execution-role` attribute in `@batch`.
2. Auto-detects the platform type from the assigned job queue to the step
3. Works with AWS Step Functions as well as local execution.

AWS Fargate support for AWS Batch

---

metaflow/plugins/aws/step_functions/step_functions_cli.py

Currently, CLI decorators can only be specified as `python flow.py --with blah step-functions create` which isn't very natural. This change allows for the following specification as well - `python flow.py step-functions create --with retry:times=3` and brings it in line with how `run` behaves

Support step-functions --with ... cli format

---

metaflow/plugins/aws/step_functions/dynamo_db_client.py

AWS Fargate doesn't support instance metadata as EC2 does, but exposes
all the metadata needed as env variables thankfully

Bug fix for AWS Step Functions on AWS Fargate

---

metaflow/plugins/aws/batch/batch_client.py

Error message should read `Job Queue *not* found` instead of `Job Queue found`

Fix typo in missing job queue error message

---

metaflow/client/filecache.py

Hello, I think there's a race condition in FileCache which can cause `get_data` to return an empty file when running in local mode. The data gets written to `tmpfile` and then renamed, but isn't necessarily flushed to disk at that point (probably not until it goes out of scope at the end of the function). So another process running ever so slightly later (in my case, due to a foreach step) sees the properly named file (since they're both on the same computer sharing that data directory) which allows it to leapfrog ahead of the other process that created the so-far empty file and access it before there's any data in the file. It happens to me when looking up successful runs of other flows inside of a foreach step that's running on a single computer. Here's what the exception looked like: …

Flush file in FileCache to fix issue where it would see an empty file

---

metaflow/datastore/datastore.py
metaflow/metaflow_config.py
metaflow/runtime.py
metaflow/task.py
metaflow/util.py

Require explicit init_task when a new datastore is actually being initialized. 
This way we can use datastore to load/store logs without any overhead.

Make datastore.__init__(mode='w') a cheap operation

---

metaflow/cli.py
metaflow/parameters.py

With this change, the help text output by:
```
python my_flow.py run --help
```
will list custom options in the intended order.
Custom parameters are iteratively inserted into the front of the command parameters list. Doing so in reverse preserves the order in which they are defined in the `FlowSpec`.

Fix ordering of custom parameters in help text

---

metaflow/plugins/aws/batch/batch_decorator.py

This PR address #348. 
Explanation (https://regex101.com/r/aPUxUr/1):
```
^(.+?(?:[:.].+?)\/)?(.*?)(?:[@:])?((?<=[@:]).*)?$
Explanation:
(.+?(?:[:.].+?)\/)? - [GROUP 0] REGISTRY
.+?                 - A registry must start with at least one character
(?:[:.].+?)\/       - A registry must have ":" or "." and end with "/"
?                   - Make a registry optional
(.*?)               - [GROUP 1] REPOSITORY
.*?                 - Get repository name until separator
(?:[@:])?           - SEPARATOR
?:                  - Don't capture separator
[@:]                - The separator must be either "@" or ":"
?                   - The separator is optional
((?<=[@:]).*)?      - [GROUP 2] TAG / DIGEST
(?<=[@:])           - A tag / digest must be preceeded by "@" or ":"
.*                  - …
```

Support images with more than one forward slash

---

metaflow/plugins/metadata/service.py

The error handling logic was missing a reference to `path`
resulting in the issue outlined in #472

Properly handle error messages in `_version` metadata call

---

metaflow/pylint_wrapper.py
setup.py

context - https://gitter.im/metaflow_org/community?at=60622af8940f1d555e277c12
Pylint barfs on `self.next` call, which can be safely ignored.

Remove pylint<2.5.0 restriction

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_decorator.py

AWS CloudWatch Logs related metadata can now be queried for
tasks that execute on AWS Batch
```
Step('Flow/42/a').task.metadata_dict['aws-batch-awslogs-group']
Step('Flow/42/a').task.metadata_dict['aws-batch-awslogs-region']
Step('Flow/42/a').task.metadata_dict['aws-batch-awslogs-stream']
```

Capture awslogs group/region/stream in task metadata

---

metaflow/cli.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/runtime.py
metaflow/util.py

The help string for `--namespace` [says](https://github.com/Netflix/metaflow/blob/de527ab8da63fa4a5895d5f6b032728769838f0a/metaflow/cli.py#L602-L607) you can pass an empty string, and it would have the same effect as `namespace(None)`.
However, it looks like this setting is never propagated to `step` command. That is, scheduler does not pass `--namespace` flag to the step process, and then namespace defaults back to username.
I have tested this in local mode and with `@batch`

Make --namespace= behave as promised

---

metaflow/decorators.py
metaflow/util.py

Allow quoted values in decospec (due to aforementioned quote)

Revert usage of shlex for Python2 (not compatible)

---

metaflow/includefile.py
metaflow/parameters.py

Click 8.0 has been released yesterday, and upgrading it seems to break `IncludeFile` and JSON parameter parsing.
For `IncludeFile` the error looks like this:
```
Traceback (most recent call last):
File "/Users/oleg/src/metaflow/metaflow/cli.py", line 987, in main
start(auto_envvar_prefix='METAFLOW', obj=state)
File "/Users/oleg/mfci/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
return self.main(args, kwargs)
File "/Users/oleg/mfci/lib/python3.7/site-packages/click/core.py", line 1059, in main
rv = self.invoke(ctx)
File "/Users/oleg/mfci/lib/python3.7/site-packages/click/core.py", line 1663, in invoke
sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
File "/Users/oleg/mfci/lib/python3.7/site-packages/click/core.py", line 927, in make_context
self.parse_args(ctx, …
```

Fix click regression

---

metaflow/datastore/util/s3util.py
metaflow/metadata/metadata.py
metaflow/runtime.py
test/core/contexts.json
test/core/metaflow_test/__init__.py
test/core/metaflow_test/cli_check.py
test/core/metaflow_test/metadata_check.py
test/core/run_tests.py
test/core/tests/basic_tags.py
test/core/tests/detect_segfault.py
test/core/tests/dynamic_parameters.py
test/core/tests/large_artifact.py
test/core/tests/large_mflog.py
test/core/tests/timeout_decorator.py

Unfortunately, it seems like the non-CLI checks for the Metaflow testing suite were disabled when the codebase was open-sourced. This PR enables those tests and fixes the regressions.

Enable non-CLI metaflow tests

---

metaflow/plugins/aws/batch/batch.py

If the docker container's entrypoint is set to `eval $@` (which many of the sagemaker images do) - that can cause invalid execution of the command that Metaflow sets.

Fix entrypoint issue with @batch

---

metaflow/metaflow_config.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/plugins/aws/step_functions/step_functions_client.py

Currently, it's hard to keep track of all the execution from within AWS console
for Step Functions executions. Now, the users can pass a `--log-execution-history`
flag to `step-functions create` to pipe execution history logs to an AWS CloudWatch
Logs log group ARN denoted by the environment variable -
METAFLOW_SFN_EXECUTION_LOG_GROUP_ARN

Enable state machine execution history logging for Step Functions integration

---

docs/concurrency.md

Rob Pike's name is mistyped in concurrency doc, fixing it.

Fix typo in docs

---

metaflow/parameters.py
metaflow/plugins/aws/step_functions/set_batch_environment.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/plugins/aws/step_functions/step_functions_cli.py

Prior to this PR, an invocation like `python flow.py step-functions create --foo-bar 42` will result in an error. Metaflow behind the scenes relies on environment variables to correctly pass parameters to various steps. The environment variables, unfortunately, can't have hyphens in the name - this PR accounts for that behavior and fixes the issue.

Handle hyphens in parameter names for AWS Step Functions executions

---

metaflow/plugins/aws/batch/batch_client.py

It seems that the response for describe_jobs could be empty,
particularly when the job has been just launched. Although, I
haven't been able to replicate the issue on my end, a handful of
Metaflow users seem to have run into it. When such an issue happens,
this PR happily ignores the response and tries again.

Add check for empty describe_jobs response for AWS Batch

---

metaflow/metadata/metadata.py
metaflow/plugins/__init__.py
metaflow/plugins/aws/step_functions/event_bridge_client.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/plugins/project_decorator.py
test/core/metaflow_test/formatter.py
test/core/tests/basic_tags.py
test/core/tests/current_singleton.py
test/core/tests/dynamic_parameters.py
test/core/tests/project_branch.py
test/core/tests/project_production.py

This PR introduces @project decorator to help users manage multiple Metaflow flows (especially on AWS Step Functions). 
[Documentation](https://docs.google.com/document/d/1NDFrPhi5-zuUkuayDg3K277-yry8Nup2fxhQGgWGzLI/edit?usp=sharing)
I will introduce namespace-aware triggering of flows in a separate PR.

Introduce @project decorator

---

metaflow/graph.py

It is hard to read the flow graph images of longer flows. This is because the node labels and graph edges are oriented in the same direction (horizontally), making the images long and thin. In contrast, orienting flow graphs from top to bottom allows more nodes to fit on a screen, making them easier to read.
I've attached two visualizations of the same toy flow, a "before" image (`left-to-right.png`) and an "after" image (`top-to-bottom.png`). Squeezing them into this PR text box unfairly accentuates the issue, because there is limited horizontal space an unlimited vertical space, but if you click through to the images, you'll see what I mean.
No worries if the left-to-right layout was a conscious decision and there's a benefit to it that I've not considered. I'd be happy to just close …

Orient flow graph images from top to bottom

---

metaflow/client/core.py

This fixes the return type of `MetaflowObject.tags` (`List` → `Set`) and suggests a minor rewording to clarify tag-based filtering.

Fix return type and clarify tag filtering

---

metaflow/runtime.py
test/core/metaflow_test/__init__.py

According to @savingoyal this hack is no longer necessary (it was introduced before this info was available in `metaflow.current`). The hack also does not work on Batch or AWS Lambda

Get rid of  _METAFLOW_RESUMED_RUN in tests

---

metaflow/mflog/save_logs_periodically.py
metaflow/mflog/tee.py
metaflow/sidecar.py
metaflow/sidecar_messages.py

1. Sidecars were borked on Python 2 since there is no native enum functionality in stdlib.
2. Mflog was borked on Python 2 as well since tee was assuming that it was launched using Python 3.
3. Remove some dead-code in MFlog implementation.

Python 2 compatibility fixes

---

metaflow/datatools/s3.py
metaflow/datatools/s3op.py

Fix for the stack trace 
```
raise MetaflowS3Exception("Getting S3 files failed.\n"\
metaflow.datatools.s3.MetaflowS3Exception: Getting S3 files failed.
First prefix requested: ('s3://blah', None)
Error: Traceback (most recent call last):
File "/Users/savin/Code/metaflow/metaflow/datatools/s3op.py", line 96, in op_info
head = s3.head_object(Bucket=url.bucket, Key=url.path)
File "/Users/savin/opt/miniconda3/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/Users/savin/opt/miniconda3/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not …
```

Fix issue with ClientError in s3.datatools

---

test/core/metaflow_test/formatter.py
test/core/run_tests.py

A few tweaks that didn't seem to deserve separate PRs.
1. Exclude more stuff from coverage
2. Copy `metaflow_test` module to the temp dir so it gets included into the code package. Without this, tests fail on AWS Lambda (as `metaflow_test` is not available to the step code )
3. Add `--inherit-env` option that makes run_tests.py pass its own env to the test (off by default).

A couple run_tests tweaks

---

metaflow/plugins/conda/conda_step_decorator.py

An error is thrown saying that the symlink already exists, that's because these 10 lines are duplicated above

Delete duplicate conda plugin code

---

metaflow/runtime.py
test/core/metaflow_test/formatter.py
test/core/tests/tag_catch.py

It is no longer necessary to have this workaround for tests, as this info is available in the `current` object.

Remove METAFLOW_ATTEMPT

---

metaflow/package.py

This enables you to package non-python files in your metaflow_custom package
and have them included when Metaflow creates the code package.

Allow Metaflow Custom packages to define additional suffixes to package

---

metaflow/plugins/__init__.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/resources_decorator.py

@resources decorator is shared by all compute related decorators -
@batch, @lambda, @k8s, @titus. This patch moves it out of
batch_decorator.py so that other decorators can cleanly reference
it.

Refactor @resources decorator

---

metaflow/metaflow_environment.py

Before v1.27, gnu tar would complain about timestamps set to 0. This was fixed ([commit](https://git.savannah.gnu.org/cgit/tar.git/commit/src/extract.c?id=28b44aaa), [discussion](https://www.mail-archive.com/bug-tar@gnu.org/msg04136.html) ) but earlier versions are still used by some docker images in the wild. This results in a lot of spam in the logs, e.g. 
```
...
2021-07-26T20:34:19.879-07:00 | tar: metaflow/package.py: implausibly old time stamp 1970-01-01 00:00:00
2021-07-26T20:34:19.879-07:00 | tar: metaflow/sidecar_messages.py: implausibly old time stamp 1970-01-01 00:00:00
2021-07-26T20:34:19.879-07:00 | tar: metaflow/trace.py: implausibly old time stamp 1970-01-01 00:00:00
2021-07-26T20:34:19.879-07:00 | tar: metaflow/task.py: implausibly old time stamp 1970-01-01 00:00:00 …
```

Silence tar timestamp warnings

---

metaflow/plugins/aws/step_functions/step_functions.py

A parameter specification like -
```
Parameter(name="test_param", type=int, default=None)
```
will result in an error even though the default has been specified
```
Flow failed:
The value of parameter test_param is ambiguous. It does not have a default and it is not required.
```
This PR fixes this issue.

Handle None as default parameters properly in AWS Step Functions

---

metaflow/client/core.py
metaflow/includefile.py
test/core/metaflow_test/cli_check.py
test/core/metaflow_test/metadata_check.py
test/core/tests/basic_include.py

`IncludeFile`s were properly returned as their content when using them as artifacts but not when accessing them via the client or the CLI. This patch fixes this behavior *for the client only*. The CLI dump command will still return an object that captures the path at which the `IncludeFile` is stored.

IncludeFile now returns the included file in the client

---

metaflow/metaflow_config.py
metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_client.py
metaflow/plugins/aws/step_functions/step_functions.py

This PR assumes that `Batch:TagResource` is whitelisted for the role which submits the AWS Batch job.
Gated on env var - `METAFLOW_BATCH_EMIT_TAGS`

Add resource tags to AWS Batch jobs

---

metaflow/client/core.py
metaflow/includefile.py
test/core/metaflow_test/cli_check.py
test/core/metaflow_test/metadata_check.py
test/core/tests/basic_include.py

Reverts Netflix/metaflow#607
Netflix/metaflow#607 breaks `step-functions create` blocking any new workflow creation.

Revert "IncludeFile now returns the included file in the client"

---

metaflow/__init__.py

This patch makes module aliasing work properly by only creating one instance of the module (with different names).

Improve module aliasing for metaflow_custom

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/batch/batch_client.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/aws/step_functions/step_functions.py

Adds an option to `@batch` decorator to mount host volumes inside the container. `@batch(mount_host_volumes="/mnt/")`. This way, `/mnt` from host will be mounted at `/mnt` inside the container. This (partially) addresses #441
In this release this is considered an _advanced_ feature due to less friendly UX and the fact that troubleshooting this requires a decent knowledge of AWS Batch. 
I've tested this on Batch and Step Functions and it seems to work!
* First class support for [per-job EFS mounts](https://aws.amazon.com/blogs/hpc/introducing-support-for-per-job-amazon-efs-volumes-in-aws-batch/). Not included this because the configuration is pretty hairy, needs some extra thinking. However, you should be able to use this PR as is to expose EFS volumes mounted at host to containers, as …

allow to mount host volumes in AWS Batch

---

metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/batch/batch_client.py

You can now do this:
```python
@batch(host_volumes=['/home', '/var/log'])
```

host_volumes for batch now takes an array instead of a csv

---

metaflow/cli.py

Proof of concept fix for #650
Caveats/Notes:
- The way this PR uses in os.environ does not appear to follow the library's conventions
- Logic avoids setting "source" and "branch" when initializing coverage if a coverage rc file is configured.   The other parameters are not conditional based on the presence of a coverage rcfile because those settings either can not be set by a coverage rcfile or are not configured in the same way
- A more complete solution might look into the coverage rcfile to validate that "branch" and "source" were configured but this would more tightly couple with coverage.py which seems like it might be a bad idea

Do not override cov params if rcfile is set

---

metaflow/plugins/aws/batch/batch_client.py

When we mount volumes from host, we need to specify volume "name". That name is really not used for anything except to refer to the volume within Batch Job Definition. We generate that name by sanitizing the original path (for a bit more debuggability). Turns out we don't sanitize enough since dots are not allowed in it. Before this fix, if you did `@batch(host_volumes="/path/with/.dot")` it would fail to execute on Batch.

Allow dots in paths in host_volumes parameter for AWS Batch

---

metaflow/exception.py
test/core/tests/task_exception.py

- Added Repr to fix error representation problem
- Added a test case to ensure this code works as expected. 
- Based on #677

Representation change for `task.exception`

---

metaflow/task.py

The decorator hook `task_pre_step` is now executed after the flow has been assigned the datastore. This change has no impact on any of the current plugin implementations.

Modify datastore availability for `task_pre_step` decorator hook

---

metaflow/plugins/aws/batch/batch.py

There was a bug in `batch.py`; this small patch fixes it. 
The following was the bug: the `self.create_job` function is given as task_spec when the function doesn't take a `task_spec` as an input.

Fixed batch related bug in convergence.

---

metaflow/plugins/aws/eks/kubernetes_client.py

From testing on our EKS cluster, it turns out `container_statuses` can sometimes be None for a failed pod. It looks like it happens when the pod was assigned to a node, haven't had a chance to start the containers yet, and gets evicted. In that case current version fails with a non-descriptive error ("NoneType not subsciptable" and a stack trace). This PR adds a handler for this case and prints a nicer error message, derived from `V1PodStatus.reason`:
```
...
2021-09-21 20:27:10.659 [6617/start/117133 (pid 14120)] Kubernetes error:
2021-09-21 20:27:10.660 [6617/start/117133 (pid 14120)] Evicted: Pod The node had condition: [DiskPressure]. . This could be a transient error. Use @retry to retry.
2021-09-21 20:27:10.760 [6617/start/117133 (pid 14120)]
```
This condition is somewhat tricky to …

K8S: better error handling for evicted pods

---

metaflow/client/core.py

Metaflow Client currently returns a string for `created_at` and `finished_at` properties. This PR changes the response type to a more appropriate Datetime object.

[Breaking] Modify return type of created_at/finished_at to datetime

---

metaflow/plugins/conda/conda.py

Was having trouble with the conda environment, and Metaflow's error was just unhelpfully:
When running...
`
python3 04-playlist-plus/playlist.py --environment=conda run --hint "Data Science"
`
Conda ran into an error while setting up environment.:
`    command '['/Users/akyrola/opt/miniconda3/bin/conda', 'info']' returned error (1): b''
`
With this PR, the error is printed clearly:
Conda ran into an error while setting up environment.:
`    command '['/Users/akyrola/opt/miniconda3/bin/conda', 'info']' returned error (1): b'', stderr=b'Traceback (most recent call last):\n  File "/Users/akyrola/opt/miniconda3/bin/conda", line 12, in <module>\n    from conda.cli import main\nModuleNotFoundError: No module named \'conda\'\n'`
Work with both py2 and py3.
Looks like my editor automatically did …

Conda _call_conda should print the stderr in case of error  

---

R/R/package.R
R/tests/testthat/test-flow.R

Defining a flow places that flow in the global environment. However, the `metaflow` function doesn't ensure that the flow is then **returned** from the global environment:
```
metaflow <- function(cls, ...) {
set_global_variable(cls, Flow$new(cls, list(...)))
get(cls)
}
```
I _think_ this happens because even though the global environment is first on the `search()` path, the `get` in this function definition is probably starting from the `metaflow` namespace. In any case, I fixed this by changing the above to `get(cls, pos = 1)`.
This popped up for me when I would define a flow with the name "test", in which case `metaflow("test")` would return the _function_ `metaflow::test`. In the test case I've implemented, I use `metaflow("sqrt")` instead, which conflicts with `base::sqrt`.

(R) Return flows from the global environment in which they're defined

---

metaflow/metaflow_config.py

**Issue** 
The s3_retry_count is read from environment variables and treated as a string. This breaks when the config value is passed to `range()` further down the line. 
**Change**
Explicitly cast the value set to S3_RETRY_COUNT in configuration to avoid such issues.

fix: Properly treat S3_RETRY_COUNT as integer

---

metaflow/plugins/debug_logger.py

An _undefined name_ in a type hint.
As done at https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/debug_monitor.py#L5 for line 27.
$ `BUILTINS=assert_equals,assert_exception,inputs,is_resumed,NUM_FOREACH,NUM_LINES,ResumeFromHere,TestRetry`
$ `flake8 . --builtins=$BUILTINS --count --select=E9,F63,F7,F82 --show-source --statistics`
```
./metaflow/metaflow/plugins/debug_logger.py:11:9: F821 undefined name 'Message'
^
```

from metaflow.sidecar_messages import Message for line 13

---

metaflow/client/core.py
metaflow/client/filecache.py
metaflow/plugins/conda/conda_environment.py

- `get_data` properly handling generator iteration
- `MetaflowCode` accidentally tried to init `BytesIO` with tuple instead of data blob

Fix two issues with MetaflowCode and get_data

---

metaflow/task.py
test/core/tests/param_names.py

Without this patch, the following flow returns an empty list for `parameter_names` - 
```
from metaflow import FlowSpec,Parameter,step
class ParameterNameFlow(FlowSpec):
x = Parameter('x',default=3,type=int)
@step
from metaflow import current
print(current.parameter_names)
@step
def end(self):
print("Done Compute")
ParameterNameFlow()
```

Fix bug with current.paramter_names

---

.github/workflows/test.yml
.pre-commit-config.yaml

This adds [pre-commit](https://pre-commit.com/) config to the repo and a GH action to run the check on PRs.
If you are a contributor, the recommendation is that you do the following (once!):
1. install pre-commit, e.g. `brew install pre-commit`
2. run `pre-commit install` in your local copy of the repo. That will install the git hook to run the checks on every commit.
From then on, you don't have to install `black` or anything, `pre-commit` will take care of it. On `git commit` you'll see either a successful run:
Or, if the formatting wasn't correct, pre-commit will fix things for you (you'll have to run `git commit` again after reviewing the changes)

Add pre-commit

---

test/core/tests/catch_retry.py

Otherwise it takes way too long on AWS batch/k8s where the default is 2 min, esp. for tests involving foreach

make catch/retry test not wait to retry

---

docs/lifecycle.dot
metaflow/cli.py
metaflow/datastore/task_datastore.py
metaflow/flowspec.py
metaflow/includefile.py
metaflow/parameters.py
metaflow/runtime.py
metaflow/task.py
test/core/metaflow_test/__init__.py
test/core/metaflow_test/formatter.py
test/core/tests/constants.py

Class members that were not parameters caused an error (regression
in 2.4.0). This addresses this issue.
This patch also clarifies and makes explicit that modifying class
variables is not safe; an error message is now raised.

Addressed an issue with class members

---

metaflow/cli_args.py
metaflow/runtime.py

closes #748
Currently, Metaflow CLI argument values that are "falsy" are ignored. The intention --- I believe --- is to omit CLI arguments that are `False`. This has the undesired consequence of also ignoring CLI arguments like `--gpu 0`, which arises from `@batch(gpu=0)`. The proposed solution explicitly ignores values in which `v is None or v is False`, allowing falsy values like `0` to go through.
Thank you to @romain-intel for help with this PR.
I couldn't find any existing tests around this functionality. I'd be happy to add a unit test if required, although I would be grateful for where this would fit into the Metaflow test suite.

Allow CLI args that are falsy but not False or None

---

metaflow/mflog/mflog.py

This PR targets this issue: https://github.com/Netflix/metaflow/issues/848
What's new:
- Import modules with respect to alphabetical order
- Remove unused module `MetaflowException`
- Elegantly check the Python version to know what modules to import
- Use a more explicit `LBYL` instead of `EAPF`

Remove unused module + enhance code patterns

---

metaflow/datatools/s3.py
metaflow/datatools/s3op.py
metaflow/datatools/s3util.py

Thanks to @romain-intel 's integration tests, he noticed that the #778 had a bug for python2:  datetime had .timestamp() function only since python 3.3.
This PR replaces the .timestamp() with a get_timestamp() function that calculates the timestamp using datetime operations.
Test with both py2 and py3:
```
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:58:04) 
[GCC Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from metaflow import S3
>>> s3 = S3()
>>> info = s3.info_many(['s3://aapo-mf-test/mnist/t10k-labels-idx1-ubyte.gz', 's3://aapo-mf-test/mnist/train-labels-idx1-ubyte.gz'])
>>> info[0].last_modified, info[1].last_modified
(1632312604.0, 1632312562.0)
>>> 
(py2) MacBook-Pro-5:metaflow akyrola$ conda activate …
```

Fix timestamp issue for python2 in s3

---

metaflow/datastore/content_addressed_store.py
metaflow/datastore/datastore_storage.py
metaflow/datastore/task_datastore.py

When an artifact is present in the blob cache, load_blobs would return
things out of order and load_artifacts would therefore return the wrong
blob for the artifact name.
This patch hopefully addresses this issue fully and also adds a small
optimization whereas blobs are not requested multiple times if they are
identical.
Fixes #819 .

Address another issue with load_artifacts

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/step_functions/step_functions.py

In the current version, SFN command line is constructed incorrectly. This PR fixes that. The problem exists since #801. 
Before #801, we used internal function `bash_capture_logs(bash_expr)` that would construct some creative bash to capture output of `bash_expr` to mflog. However, since this implementation used [bash process substitution](https://tldp.org/LDP/abs/html/process-sub.html), it wouldn't work on AWS Lambda. Therefore it was replaced with another implementation, that would kick off a wrapper subprocess via `python -m metaflow.mflog.redirect_streams ...`.
As part of this, the internal function `bash_capture_logs(bash_expr)` was replaced with `capture_output_to_mflog(command_and_args)` that would do the necessary wrapping. However, the new implementation would no longer be able …

Use mflog redirect_stream wrapper correctly with Step Functions

---

metaflow/cli.py
metaflow/client/core.py
metaflow/datastore/task_datastore.py
metaflow/task.py
test/core/tests/resume_originpath.py

We currently don't store `task-id` of the origin task for resumed workflows. 
- Added `origin_pathspec` to metaflow client to retrieve the pathspec of the origin task. 
- Added `origin-task-id` to `Task` metadata

`origin-task-id` in `Task` metadata and `origin_pathspec` property in `Task` object

---

test/core/contexts.json

Remove py2 test texts.
Python2 is becoming hard to maintain as the direct or indirect dependencies start becoming py2 incompatible

Remove python2 test contexts

---

metaflow/datatools/s3util.py

When`METAFLOW_S3_RETRY_COUNT=0`  the `get_cards` functions fails because `CardDatastore._list_card_paths` calls `S3Storage.list_content`; This class uses `s3op.py` (which uses `s3util.py` ). These files use the `S3_RETRY_COUNT` property of `metaflow_config`. 
In all other files except for `s3util.py` `S3_RETRY_COUNT` is iterated over in the following way: `range(S3_RETRY_COUNT +1)`; Here is it is iterated over `range(S3_RETRY_COUNT)`. 
This seems to be a bug and this PR fixes it.

`aws_retry`'s `S3_RETRY_COUNT` kept min at 1

---

metaflow/plugins/aws/batch/batch_client.py

There is a somewhat obscure difference in a way list attributes are handled between SFN and "standalone" AWS Batch. If the attribute is a list of strings, but the user passes a single string instead, it is implicitly converted to a single-item list when we convert attributes to command-line args for `batch_cli.py` and they are parsed back to Python objects by `click`. However, that conversion does not happen when used with SFN. 
Support both single strings and lists for `host_volumes`
A proper solution would be to more explicitly support list attributes in decospec parser used for `--with`, and have unit tests for that. Right now it just kinda happens to (mostly) work.

fix argument type handling for host_volumes when used with --with and SFN

---

metaflow/plugins/cards/card_modules/bundle.css
metaflow/plugins/cards/ui/src/app.css

Some tables, at some browser widths had a slight horizontal scroll.
e.g.
https://ui.oleg2.dev.outerbounds.xyz/CustomCardFlow/5689/end/128841?direction=asc&group=true&order=startTime&section=stderr
Made a fix by removing the `border-collapse` and replacing it with `border-spacing: 1px` while removing the white border on the table cells.

Fixed horizontal scroll on tables

---

test/core/tests/card_timeout.py

Rebasing #612 and friends, `black .` is showing this unrelated change. I folded it into #661 but [the CI is failing there for a reason I'm not sure is due to my changes](https://github.com/Netflix/metaflow/pull/661#issuecomment-1006693763), so I'm submitting this separately partly to see if I see the same failure here.

fix `black .` issue

---

metaflow/plugins/aws/batch/batch_client.py

`execute()` is only called [here](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/aws/batch/batch.py#L321:L321), but that code calls `create_job()` right before that, which in turn calls `job_def()`, which populates `jobDefinition` in `self.payload`.
The unused code inside `if` has been broken for a while anyway: over the last few months, two more required parameters were added to `_register_job_definition()`, namely `num_parallel` and `host_volumes`. That's how I noticed it is not used -- pylance type checker highlighted it for me as an error.

Remove unused code in BatchJob.execute()

---

metaflow/plugins/env_escape/server.py

This was a nasty "typo" (the same line is present elsewhere correctly)
and caused the wrong "overrides" module to be loaded if you had, for
example, the "overrides" module installed (yes, there is such a thing)

Fix incorrect import in env escape server process

---

metaflow/plugins/aws/step_functions/step_functions.py

As title. Now `step-functions create` fails.

Fail early step function create with @parallel.

---

metaflow/datastore/task_datastore.py
metaflow/metadata/util.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/aws/eks/kubernetes_decorator.py

Artifacts were persisted *after* the metadata was saved to S3 to be
repatriated locally which caused it to completely miss.
This addresses this issue (fixes #878) and also addresses another issue
in load_metadata when loading non existent metadata.

Fix issue when running on batch with local metadata

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_client.py
metaflow/plugins/aws/batch/batch_decorator.py

Fixes major bug of running AWS Batch parallel with num_parallel=1. There was  a couple of incorrect num_parallel > 1 while they should be num_parallel >= 1. 
Tested with
`   python  test/parallel/parallel_test_flow.py --no-pylint   --with batch run --num_parallel=1
`and
`    python  test/parallel/parallel_test_flow.py --no-pylint   --with batch run --num_parallel=4
`
Also more compact logging of the statuses of child nodes while starting up:
```
Task is starting (status RUNNING)...  (parallel node status: [SUBMITTED:3])
```

Fix issue with @batch and num_parallel=1; improve status log.

---

test/unit/test_compute_resource_attributes.py

You can run it manually like this:
```bash
cd test/unit
PYTHONPATH=../../ python -m pytest
```
It is not yet hooked up to github actions but that'll come in a separate PR

Add a unit test for compute_resource_attributes

---

.github/workflows/dummy.yml
.github/workflows/publish.yml
.github/workflows/test.yml
metaflow/datastore/flow_datastore.py
metaflow/datastore/task_datastore.py
test/core/run_tests.py

- Ported changes to GH action tests from #940 
- Python3.5 is not playing nice with bytes-based JSON loading. Throws an error like [TypeError: the JSON object must be str, not 'bytes'](https://stackoverflow.com/questions/42683478/typeerror-the-json-object-must-be-str-not-bytes). This error doesn't persist in py3.6+. This resulted in minor changes to the way we read task metadata in task_datastore.py and flow_datastore.py
- The tests in the `publish.yml` are refactored to come from `test.yml`. We reuse the jobs in the Test gh action. Workflows being reused need to have [on.workflow_call](https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow). This helps reuse [it locally](https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can- …

Python Multi Version Test Suite

---

metaflow/cli.py

Added a flag `--json` flag in the `output-raw` command.

Exporting graph in JSON format via `output-raw` cli command 

---

metaflow/plugins/cards/card_cli.py
test/core/metaflow_test/cli_check.py
test/core/tests/card_default_editable.py
test/core/tests/card_default_editable_customize.py
test/core/tests/card_default_editable_with_id.py
test/core/tests/card_id_append.py
test/core/tests/card_import.py
test/core/tests/card_resume.py
test/core/tests/card_simple.py

This PR helps resolve some hacky code added to the card test suite where we checked stdout to validate if a command threw a specific error. This was a brittle solution. Patching for something that is more conventional. By explicitly piping errors from stderr. 
- Added `--file` arg to `card list` cli
- Using files to get the information written by cli
- changes to test to use files instead of stdout
- Piping std errors to stderr to capture card not found errors.

Fixing some hacky plumbing in card test suite

---

metaflow/datastore/s3_storage.py
metaflow/metaflow_config.py

This addresses https://github.com/Netflix/metaflow/issues/990 by
1. Adds `METAFLOW_ARTIFACT_LOCALROOT` to the configuration. It defaults to `os.getcwd()`
2. When instantiating the `S3` object in `metaflow/datastore/s3_storage.py`, use that configurable value instead of `os.getcwd()`
I tested this locally by adding `"METAFLOW_ARTIFACT_LOCALROOT": "/tmp/"` to my `~/.metaflowconfig/config.json` file, and then pulling some artifacts via `task.data`. It did indeed create a `/tmp/metaflow.s3.br9v3iit` instead of going in the current directory.

Configurable temp root when pulling artifacts from s3

---

.pre-commit-config.yaml
metaflow/client/filecache.py
metaflow/plugins/cards/card_modules/chevron/renderer.py
metaflow/plugins/env_escape/data_transferer.py

Alternative solution to https://github.com/Netflix/metaflow/pull/998
The black version 21.9b0 doesn’t work with new [click](https://pypi.org/project/click/#history) version 8.1.0 released on Mar 28, and it’s fixed by [black](https://pypi.org/project/black/#history) version 22.3.0 released on the same day. 
However black version 22.3.0 doesn't support python 2. Instead pinning an older version of click in pre-commit hook allow us to keep python 2 compatibility.
Pin latest version of click that stays compatible with black 21.9b0

Pin older click compatible to old black

---

metaflow/current.py

Address issue #1011 
While `current` usage outside of a running Flow is not part of [normal usage](https://docs.metaflow.org/metaflow/tagging#accessing-current-ids-in-a-flow), it is trivial to change to achieve more consistent behavior.

current.pathspec to return None when used outside Flow

---

metaflow/plugins/cards/card_cli.py

- `echo_always` defaulted to stderr instead of stdout:(

Fixing bug in the `card list` command

---

metaflow/metadata/metadata.py
metaflow/plugins/metadata/local.py
metaflow/plugins/metadata/service.py
metaflow/util.py
test/core/tests/resume_end_step.py

This is part of project to add tag mutation support. RFC [here](https://www.notion.so/outerbounds/RFC-Implementing-tag-mutation-98ef6ba39aee4aeeb9c6150b4cffea2a) (see "Consolidate tagging to Runs")
A side effect of consolidating tagging to Runs on the read paths is that Task-level tags and system_tags are no longer accessible over the Metaflow client API - we will get only Run-level tags and system tags.  In most cases this is fine because usually tags are the same between a Run and its descendant Tasks.  The exception is Task-level system tags which may diverge from the Run's system tags in some rare situations.
In this PR:
* We explicitly name the information being stored as system tags (including at Task-level) "system information"
* For tasks, we _continue_ to store this "system …

[tag-mutation-project] Stash system info in task metadata

---

metaflow/plugins/metadata/local.py
metaflow/plugins/metadata/service.py

This was spotted manually.  Test suite did not catch this.
In terms of prevention, this class of error is best caught with static type checking (TBD!).  Failing that we can consider if pylint can help here.

Fix _new_task calling bug in LocalMetadataProvider

---

metaflow/cli.py
test/core/contexts.json
test/core/tests/resume_start_step.py
test/core/tests/run_id_file.py

This matches behavior for a non-resume (regular `flow.py run`).  This way is simply more useful, following user feedback.
Core test added.

Run id file should be written prior to execution when resuming

---

metaflow/__init__.py

This makes the use of `metaflow.current` more consistent across plugins. Without this change, things that use `metaflow.current` before the line referring to current get a module as opposed to the singleton.

Reorder imports in metaflow/__init__.py

---

metaflow/client/core.py
metaflow/metadata/metadata.py
metaflow/plugins/metadata/local.py
metaflow/runtime.py
test/unit/test_local_metadata_provider.py

This is part of project to add tag mutation support. RFC [here](https://www.notion.so/outerbounds/RFC-Implementing-tag-mutation-98ef6ba39aee4aeeb9c6150b4cffea2a) (see "Consolidate tagging to Runs")
This is analogous to [this change](https://github.com/Netflix/metaflow-service/pull/315) on metadata service.
The main changes are on `LocalMetadataProvide._get_object_internal`.  We retrieve the ancestral Run of every object being returned, and replace `tags` and `system_tags` fields in the objects with the Run's tags before returning.
`LocalMetadataProvider._get_object_internal` returns a collection of objects of a certain type (controlled by `sub_type`), under a certain scope (controlled by `obj_type`).  There are multiple rules governing how `obj_type` and `sub_type` relate to each other. …

[tag-mutation-project] Local metadata provider - object read paths to return ancestral Run tags

---

metaflow/__init__.py
metaflow/cli.py
metaflow/event_logger.py
metaflow/metadata/heartbeat.py
metaflow/mflog/save_logs_periodically.py
metaflow/monitor.py
metaflow/plugins/__init__.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/plugins/debug_logger.py
metaflow/plugins/debug_monitor.py
metaflow/plugins/kubernetes/kubernetes_decorator.py
metaflow/plugins/metadata/service.py
metaflow/runtime.py
metaflow/sidecar.py
metaflow/sidecar/__init__.py
metaflow/sidecar/sidecar.py
metaflow/sidecar/sidecar_messages.py
metaflow/sidecar/sidecar_subprocess.py
metaflow/sidecar/sidecar_worker.py
metaflow/sidecar_messages.py
metaflow/sidecar_worker.py
metaflow/task.py

Several changes:
- allow side-passing of a static "context" to the sidecar process to keep
messages as small as possible
- clean up the interfaces and make it clearer what is what (ie: there is
an emitter inside the process and then a sidecar that runs outside)
- better error checking
- better handling of shutdown (sidecars will now properly get a shutdown
message giving them the opportunity to clean up -- this may add a bit
of latency at the end of the program execution.
Also improved message when plugins don't load in case of an issue with
Metaflow extensions

Improve sidecar message handling

---

metaflow/plugins/env_escape/__init__.py

When a module configured in the env escape was present in the local
environment, we would raise an error. We now print a message and use
the module present in the environment (not the environment escape).
This allows the env escape modules to provide a "fallback" in case the
module is not present but to still use the local module if present

Change behavior of env escape when module is present

---

metaflow/datatools/s3util.py
metaflow/metaflow_config.py

We have seen issues this utility. We print to stderr when we are retrying on an exception that gets fixed on one or more retries. However, the user perceives this to be an `ERROR` when actually it is merely a `WARNING`. This PR fixes this issue by adding a `[WARNING]` prefix and only printing this warning when a certain amount of retries have been made.

Changed error to warning in AWS retry

---

metaflow/datatools/s3op.py

In its current location, this could modify the sys.path of the current
running metaflow which could have nefarious consequences with the escape
hatch which uses sys.path to determine the outside environment's python path.
The following scenario would cause issues:
- metaflow is installed in the usual path on the system
- a conda environment was manually bootstrapped from a directory A.
+ at this point, sys.path starts with `A` and then contains the other
system includes
+ s3op.py is imported at some point by the Conda installer when it calls `get_many`
+ this modifies sys.path to insert, at the beginning, the parent of Metaflow; so
in this case, sys.path looks something like
['/apps/python3/lib/python3.7/site-packages', 'A', '/apps/python3/lib/python3.7/site-packages'...]
+ when the …

Move a sys.path modification in s3op to __main__

---

metaflow/decorators.py
metaflow/metaflow_config.py
metaflow/plugins/__init__.py
metaflow/plugins/airflow/airflow.py
metaflow/plugins/airflow/airflow_cli.py
metaflow/plugins/airflow/airflow_decorator.py
metaflow/plugins/airflow/airflow_utils.py
metaflow/plugins/airflow/dag.py
metaflow/plugins/airflow/exception.py
metaflow/plugins/airflow/plumbing/set_parameters.py

The following are the key user-related constructs exposed by metaflow to support the Airflow universe:
- A CLI command to create airflow workflow DAG file from metaflow `FlowSpec`. 
Metaflow users can now easily compile Metaflow workflows into Airflow compatible workflows. Every Metaflow `FlowSpec` file exposes a `airflow create` command to compile the workflow into an Airflow DAG file. Under the hood metaflow packages the code packages, stores them in S3 and then compiles the code into a airflow compatible python file. The generated file can be moved to the Airflow scheduler's DAGs folder. From there the scheduler will run the workflow as a native airflow workflow. 
Metaflow requires Kubernetes as Airflow's compute-execution medium. Metaflow leverages the Airflow `KuberneterPodOperator` …

Airflow Support

---

metaflow/plugins/env_escape/__init__.py

This PR aims to solve a bug related to importing multiple packages using `env_escape` when one of these packages are available locally. The steps to reproduce are given below:
```
import package A # available locally
class Flow():
import package B # not available locally
```
`env_escape` fails for package B since we fail to update the `sys.path` when using the package A that is available locally.

Fix for env_escape bug when importing local packages

---

metaflow/plugins/cards/card_client.py

get_cards would not always respect a Task's ds-root leading to cases
where a Task has cards but they cannot be accessed because of an invalid
path.

Fix an issue with get_cards not respecting a Task's ds-root

---

metaflow/mflog/mflog.py

Fixes issue https://github.com/Netflix/metaflow/issues/680

Fix DeprecationWarning on invalid escape sequence

---

metaflow/cli.py
metaflow/debug.py
metaflow/decorators.py
metaflow/plugins/__init__.py
metaflow/plugins/cards/card_decorator.py
metaflow/plugins/conda/conda_step_decorator.py

This cleaned up a few uses of the decospec where individual plugins were having to parse the decospec.
Two other minor changes to improve error message and allow for echoing without a nl

Use json to dump/load decorator specs.

---

metaflow/plugins/env_escape/client.py
metaflow/plugins/env_escape/client_modules.py
metaflow/plugins/env_escape/communication/socket_bytestream.py
metaflow/plugins/env_escape/data_transferer.py
metaflow/plugins/env_escape/server.py

- Properly handle the case of multiple `overrides` for different escaped libraries (previously, only the first override was considered)
- Add datetime.timedelta to the list of simple types transferred
- Allow the specification of override functions (and getattr/setattr) on additional proxied types.

Env escape improvements and bug fixes

---

test/core/metaflow_extensions/test_org/plugins/frameworks/pytorch.py
test/core/metaflow_extensions/test_org/plugins/mfextinit_test_org.py
test/core/tests/extensions.py

This PR adds a test that checks that the `_orig` module is accessible when a module is overwritten through extensions framework.

Add test that orig module is accessible

---

metaflow/extension_support.py
test/core/metaflow_extensions/test_org/plugins/frameworks/pytorch.py
test/core/metaflow_extensions/test_org/plugins/mfextinit_test_org.py
test/core/tests/extensions.py

This addresses an issue where submodules like `mymodule._orig.submodule` would not load properly.
This will properly load things like `from .foofa import xyz` from a module or sub-module in the original location but currently does not work if the import path is absolute.

Fix `._orig` access for submodules for MF extensions

---

metaflow/decorators.py

We are running into a `ValueError` setting node selectors with `kubernetes` decorators. The issue is that we're trying to split a string that looks like `node_selector=["node.kubernetes.io/instance-type=g5.xlarge"]`, which happens to have two equal signs. This PR updates to split only on the first one.

allow equal sign in decorator spec values

---

.github/workflows/test.yml

Ubuntu latest which maps to 22.04 doesn't support Py 3.5/3.6 on GH actions

Pin GH tests to Ubuntu 20.04

---

metaflow/plugins/kubernetes/kubernetes_decorator.py

GPU resources were not getting propagated when used "--with kubernetes". Now, it does.
Testing Done:
- Reproduced the problem creating a step with a decorator @resources(gpu=1) and running it "--with kubernetes". The pods were scheduled without gpus.
- Verified that after the fix, the pods were scheduled with gpus (request and limit).

Set gpu resources correctly "--with kubernetes"

---

metaflow/metaflow_config.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/kubernetes/kubernetes.py
metaflow/plugins/kubernetes/kubernetes_cli.py
metaflow/plugins/kubernetes/kubernetes_decorator.py
metaflow/plugins/kubernetes/kubernetes_job.py

This PR adds support for `tolerations` in the Kubernetes and Argo plugins.
Testing Done:
Using the script `flow.py`
```python
DEFAULT_RESOURCES = {"cpu": "1", "gpu": "0", "memory": "1"}
from metaflow import (
FlowSpec,
step,
timeout,
kubernetes,
resources,
)
class TestTolerationsFlow(FlowSpec):
@resources(**DEFAULT_RESOURCES)
@step
"""
This is the 'start' step. All flows must have a step named 'start' that
is the first step in the flow.
"""
@resources(**DEFAULT_RESOURCES)
@step
def end(self):
"""
This is the 'end' step. All flows must have an 'end' step, which is the
last step in the flow.
"""
print("TestTolerationsFlow is all done.")
TestTolerationsFlow()
```
Tested the following commands:
- `python3 flow.py run --with …

Add support for Kubernetes tolerations

---

setup.py

Without this, if you run mypy on code that uses Metaflow, it will [complain](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker) about type stubs missing. 
https://peps.python.org/pep-0561/#packaging-type-information

Since we're now providing type annotations, add typed marker as per PEP-561

---

metaflow/plugins/argo/argo_client.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/step_functions/schedule_decorator.py
metaflow/plugins/aws/step_functions/step_functions.py

This PR adds support for specifying a timezone when scheduling Argo workflows.
The relevant Argo documentation is here: https://argoproj.github.io/argo-workflows/cron-workflows/#cronworkflow-options

support timezone when scheduling with Argo workflows

---

metaflow/extension_support/plugins.py
metaflow/metaflow_config.py
metaflow/plugins/__init__.py
metaflow/plugins/airflow/airflow.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/secrets_manager/aws_secrets_manager_secrets_provider.py
metaflow/plugins/kubernetes/kubernetes.py
metaflow/plugins/secrets/__init__.py
metaflow/plugins/secrets/inline_secrets_provider.py
metaflow/plugins/secrets/secrets_decorator.py
test/core/tests/secrets_decorator.py
test/unit/test_secrets_decorator.py

RFC doc: https://docs.google.com/document/d/1vhU7lLZo1znF6of_cE8KewNae99_fUBsaoFHhW8FJew/edit#heading=h.tt3aazlsd22b 
This PR implements the general @secrets decorator interface, as well as AWS Secrets Manager backend.
How to use `@secrets(sources=[...])`?  `sources` is a list of strings or dictionaries.
String-style will cover most users with vanilla requirements (secret payload are JSON objects, to be unrolled as env vars).
Dictionary-style will allow specification of provider specific `options`.  For AWS here, the `json` option allows disabling of JSON parsing, in case the secret payload string is not the right kind of JSON (or not JSON at all).  `region` also allows control of which region's Secret Manager to use.
`inline` secrets provider type is included for testing purposes …

Implement @secrets, with AWS support

---

metaflow/plugins/env_escape/__init__.py

If there was no __init__.py file in an extension for env escape (which is the recommended way), the configurations would fail to load and crash Metaflow.

Fix an issue with configurations for env escape extensions

---

metaflow/extension_support/__init__.py
metaflow/extension_support/_empty_file.py
metaflow/package.py

This will force the packaged `metaflow_extensions` package to not be a namespace package and therefore prevent python from looking for other extensions that may be present on the remote system thereby giving the user the exact same metaflow environment as the one they had locally.
In particular, this closes off a sort of "code injection" possibility.

When packaging `metaflow_extensions`, add an empty `__init__.py` file.

---

metaflow/client/core.py
metaflow/package.py
metaflow/plugins/conda/conda_step_decorator.py

The name "INFO" was used in disparate parts of the code and could leade to inconsistencies. This homogeneizes the use

Replace instances of "INFO" with a constant

---

metaflow/plugins/airflow/airflow.py
metaflow/plugins/airflow/airflow_cli.py

There was a bug in the token retrieval code that would never retrieve the token. This PR fixes it. It uses `is_file` instead of `list_content` to check for token existence. Using `list_content` was the main cause of the bug.

Airflow Token creation bug fix

---

metaflow/plugins/environment_decorator.py

On `master`, running this flow:
``` python
from metaflow import environment  # noqa F0401
from metaflow import FlowSpec, step
class MyFlow(FlowSpec):
"""Test non-str values passed to environment decorator."""
@environment(vars={"FOO": 1})
@step
"""Start."""
@step
def end(self):
"""End."""
pass
```
elicits an opaque error:
``` python
Metaflow 2.7.22.post2+git2f9e443 executing MyFlow for user:dpoznik
Validating your flow...
The graph looks good!
Running pylint...
Pylint is happy!
2023-02-18 00:18:58.104 Workflow starting (run-id 1676708338093700):
2023-02-18 00:18:58.108 Workflow failed.
2023-02-18 00:18:58.108 Terminating 0 active tasks...
2023-02-18 00:18:58.108 Flushing logs...
Internal error
Traceback (most recent call last):
File …
```

Cast values to `str` before passing to environment

---

metaflow/plugins/conda/conda.py

This fixes https://github.com/Netflix/metaflow/issues/1293
There shouldn't be a reason to check for the existence of `/env/` in the pathname, because there are already checks to see if the environment matches the flow ID

remove check for '/envs/' in conda pathname

---

metaflow/plugins/argo/argo_workflows_cli.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/runtime.py

emits UI URL after triggering a workflow with either Argo, or step functions
relates to #1292

feature: emit UI url for argo workflows and step-functions

---

metaflow/datastore/datastore_set.py
metaflow/datastore/flow_datastore.py

When the `logs` command was invoked, it would go and figure out the task_datastores it needed to get the logs from. In some cases (when an attempt was started but not finished), it would try to access the data file for the datastore (even though it didn't exist). It is actually not needed in this particular case so this PR modifies the code to ignore that.

Fix the `logs` command in cases where the step/task hasn't finished

---

.github/workflows/metaflow.s3_tests.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Pin action versions with hashes in GitHub actions as per security recommendations
in preparation for #1333

fix: GitHub Workflow security recommendations

---

metaflow/cmd/main_cli.py
metaflow/metaflow_config.py

Also minor change to display the proper Metaflow version (including extension info) in the command line tool

Make the contact information displayed by the Metaflow command configurable

---

metaflow/plugins/cards/card_modules/convert_to_native_type.py

This PR helps close #1319 . Here is a test flow to verify that things are working okay: 
```python
from metaflow import FlowSpec, step, Parameter, IncludeFile, catch, card
import math, time, uuid, datetime, random, string, sys
from decimal import Decimal
import requests
class CustomClass():
def __str__(self):
return 'a' * int(1024**2)
def __repr__(self):
return str(self)
class DefaultCardFlow(FlowSpec):
str_param = Parameter('str_param', default='刺身は美味しい')
file_param = IncludeFile('file_param')
json_param = Parameter('json_param', default='{"states": {[{"CA", 0}, {"NY", 1}]}')
float_param = Parameter('float_param', default=math.pi)
@card
@step
"""
This step creates a bunch of artifacts of various kinds. They
should show up nicely on the default card 🔬.
""" …
```

Safely parse `pandas.DataFrame` for `default` card

---

metaflow/plugins/metadata/service.py

The code for starting the heartbeat calls version() multiple times even when the actual value of the version is already available. Each call to version() makes a round-trip to the metadata-service which increases the overall latency.
This change simply uses the value of the first call to version() in subsequent checks avoids 2 extra rtts the metadata service.

Reduce multiple metadata service rtts using cached version.

---

metaflow/plugins/env_escape/communication/channel.py

JSON.loads api changed in version 3.9: The keyword argument encoding has been removed.
See detail in https://docs.python.org/3.9/library/json.html?highlight=json%20loads#json.load
Remove the encoding should be find, since "utf-8" is the default encoding.

Remove encoding for JSON.loads

---

metaflow/client/core.py

relates to #1114 
The autocomplete for objects works with this simple addition of returning children ids. Suggestions when initiating classes like `Flow("` could be helpful too but I couldn't find a way to do this. But for the class instances of Flow, Run, Step, Task, the autocomplete works and for reference the options are printed by calling the function that ipython would use.
Any thoughts @romain-intel ?
```
from metaflow import Flow, Metaflow
Metaflow().flows
>>> [Flow('HelloFlow'), Flow('MovieStatsFlow')]
flow = Flow('HelloFlow') # No autocomplete here
flow._ipython_key_completions_()
>>> 
['1680815181013681',
'1680815178214737',
'1680432265121345',
'1680430310127401']
run = flow["1680815178214737"]
run._ipython_key_completions_()
>>> ['end', 'hello', 'start']
step = run["hello"] …
```

feat: add ipython autocomplete support for MetaflowObject instances

---

metaflow/client/core.py

Loops over steps of the run and return step.task.code if present.
Test flow with intermediate non-local step.
```
from metaflow import step, FlowSpec, conda_base, kubernetes
class HelloFlow(FlowSpec):
@step
print("Starting 👋")
self.next(self.eat)
@kubernetes
@step
def eat(self):
print("Eating 🍜")
@step
def end(self):
print("Done! 🏁")
HelloFlow()
```
Checking code with metadata
```
In [1]: from metaflow import Flow
In [2]: run = Flow("HelloFlow").latest_successful_run
In [3]: run.code
Out[3]: <metaflow.client.core.MetaflowCode at 0x7f28273010a0>
```
closes #1322

Fix: Check all steps for MetaflowCode and return if any

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_client.py

tmpfs folder is not correctly being set by only passing `tmpfs_size=` in the batch decorator.
example:
`@batch(memory=500, tmpfs_size=1100)`
the `current.tempdir` will remain as `.` instead of changing to `/metaflow_temp` 
cause for the issue is due to `use_tmpfs` having "False" as a default from the decorator, not the assumed `None` that is being passed around elsewhere

fix: batch tmpfs enabling logic

---

metaflow/client/core.py
metaflow/exception.py

related to #948 
- Adds `MetaflowInvalidPathspec` exception
- Validates `pathspec` for all 5 MetaflowObjects - Flow to Artifact
- Changes unnecessary id re-assignment for MetaflowObjects created using `pathspec`
I have looked into writing test case but couldn't see that there are any specifically for testing metadata. Please let me know. Thanks

Fix: Validate pathspec argument for MetaflowObject

---

metaflow/client/core.py

The newly added `_namespace_check` attribute in the `MetaflowObject` broke backward compatibility in cases where the object is deserialized from an older version of Metaflow. 
Steps to reproduce this issue:
- Launch a flow with OSS version `2.8.0` that saves the Run object as a flow artifact
- Try to access the artifact (which a Run object) from a new flow that is running on version `2.8.3`
- You will see an error like this `AttributeError: 'Run' object has no attribute '_namespace_check'`
This is because the Run object is pickled in the original flow when it is assigned to an artifact. In the other flow, it is unpickled to the old Run object that does not contain the newly added attribute.
This PR adds a custom implementation of the `__getstate__` and `__setstate__` functions to help …

Fixing a MetaflowObject backward compatibility issue

---

metaflow/plugins/argo/argo_workflows_cli.py

can be re-enabled as part of 2.9.0 release.

mute argo event emmission

---

metaflow/cmd/configure_cmd.py

- added `METAFLOW_PROFILE` environment variable value as a default for most of the `metaflow configure [cmd]` options.
Still undecided if this should be used as a default for the `sandbox/azure/aws/gcp/kubernetes` commands
addresses #1302

fix: make metaflow config aware of profile environment variable

---

metaflow/R.py

move away from deprecated `imp` in favor of `importlib`
addresses #1380

fix: migrate R support to use importlib

---

metaflow/metaflow_config.py
metaflow/plugins/airflow/airflow.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/kubernetes/kubernetes.py
metaflow/plugins/kubernetes/kubernetes_cli.py
metaflow/plugins/kubernetes/kubernetes_decorator.py
metaflow/plugins/kubernetes/kubernetes_job.py

- Add support for Kubernetes (and Argo Workflows) to mount existing PersistentVolumeClaims for pods.
Addressing #1117 and possibly the use-case in #1362 as well.
Feature checklist and usage reference

feature: add Kubernetes support for PVC mounts

---

metaflow/plugins/env_escape/client.py

When importing the overrides.py file, we would insert a path in sys.path which could potentially leak packages from the outside environment in.

Fix an issue with the escape hatch that could cause outside packages to "leak"

---

metaflow/plugins/env_escape/client.py
metaflow/plugins/env_escape/client_modules.py

This allows the pattern:
```
try:
import foo
except ImportError:
pass
```
to work as expected. Currently, it could raise a RuntimeError which would then propagate back to the user.

Wrap errors importing over the escape hatch as ImportError

---

metaflow/metaflow_config.py
metaflow/metaflow_config_funcs.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/batch/batch.py
metaflow/plugins/datatools/s3/s3.py
metaflow/plugins/datatools/s3/s3op.py
metaflow/plugins/kubernetes/kubernetes.py
test/data/s3/test_s3.py

This PR allows users to enable Server-Side Encryption (SSE) for S3 uploads through the use of the  `METAFLOW_S3_SERVER_SIDE_ENCRYPTION` configuration setting.
See [this PR](https://github.com/Netflix/metaflow/pull/1382) for prior conversations regarding the topic.

feat: ability to use ServerSideEncryption for S3 uploads

---

metaflow/plugins/airflow/airflow.py

- There was a bug overwrote the env values set in the environment decorator
- This made the env decorator export all metaflow related env values in the cli instead of the ones set via the cli.

[bugfix] support `--with environment` in Airflow

---

metaflow/plugins/aws/step_functions/event_bridge_client.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/plugins/aws/step_functions/step_functions_client.py

- additional changes on top of #1284 branch
- unable to open a PR targeting the fork branch, possibly simply not permitted.
Would prefer if original author would incorporate these into their own branch so #1284 can be merged. Otherwise pick one of the following strategies:
- this PR supersedes #1284
- merge #1284 in, crediting the original author. I'll Rebase this PR and merge afterwards.

feat: sfn delete workflow (with prod token validation and messaging)

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_cli.py

The new CLI commands for argo-workflows that accept a `run_id` have had a pending issue regarding production token authorization, and lacking any guard against passing an arbitrary run_id to a flow file that the user has a valid production token for.
This PR introduces checks for
- the run_id is of the same flow_name as the CLI command was issued on
- the run_id is of the same project and branch as the CLI command was issued on
- the user issuing the command has a production token for the workflow with the run_id
- the run_id is for an Argo Workflow (existing prefix check, simply moved it to the same validation function)

feature: add validation for what flow the run_id belongs to

---

metaflow/plugins/aws/secrets_manager/aws_secrets_manager_secrets_provider.py

Its not uncommon and even seems to be recommended by AWS to use `/` in AWS Secret Manager secret names. If used in conjunction with non-JSON secrets, it leads to issues here since we use secret name as environment variable name, and that can't contain `/`

sanitize / in secret names

---

metaflow/plugins/argo/argo_workflows.py

Fix handling spaces in argo events payload when mapping payload values to parameters.
Tested that this does not re-introduce the double quoting bug for regular parameter usage. Tried out different Sprig functions for escaping, including `squote` and `quote`, but settled with `toJson` in order to escape errant quotes in the middle of the inputs.
Encountered some funky behavior with Argo events parameter handling: when using `dataTemplate`, if the template execution fails (for example due to providing a non-existant jsonpath), the workflow will not fail, instead it will fallback to the default parameter values provided in the sensor. This was a bit of a head scratcher during testing.
Addresses #1458

fix: Argo events parameters with spaces

---

metaflow/plugins/aws/secrets_manager/aws_secrets_manager_secrets_provider.py

Follow up for https://github.com/Netflix/metaflow/pull/1470. This adds an option to customize environment variable name to use to store secret value when used with AWS version of `@secrets` decorator, and it only applies when the secret is _not_  formatted as a JSON dict (otherwise we just use JSON key as env var as before).

allow to customize env var name in @secrets

---

metaflow/plugins/datatools/s3/s3.py
metaflow/plugins/datatools/s3/s3op.py

fixes bug with S3 ServerSideEncryption headers affecting S3 operations (`get_many / get_recursive / get_all / put_many`)

fix: s3 op bug with ServerSideEncryption

---

metaflow/plugins/aws/batch/batch_decorator.py

add validation for the Batch decorator that checks that an `iam_role` is configured (either through the decorator, or with an environment variable).
Currently if `METAFLOW_ECS_S3_ACCESS_IAM_ROLE` is not configured, trying to run a flow with `--with batch` or deploying with step-functions will fail to an error
```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter containerProperties.jobRoleArn, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

fix: validate required configuration for Batch

---

metaflow/metaflow_environment.py
metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/conda/conda_environment.py
metaflow/plugins/kubernetes/kubernetes_cli.py

This allows a user to specify an executable and have that executable only be used for non Conda steps.
Note that currently there is no direct way to specify the executable for batch/kube although the functionality is half present.

Pass the user-defined executable to environment's `executable`

---

metaflow/task.py

Has no utility at its current spot and makes the lifecycle.png diagram more accurate.

Remove validate_environment from task lifecycle

---

metaflow/plugins/datatools/s3/s3.py

I recently encountered the issue raised in I[ssue 863](https://github.com/Netflix/metaflow/issues/683). 
I note that there is an existing [PR](https://github.com/Netflix/metaflow/pull/853) on this issue. However, it is very old and I assume now dead. As a result, I have made a new PR that addresses the comments in the original PR.

Fix/863 - Improve error message in metaflow.S3 class when DATATOOLS_S3ROOT is not configured.

---

metaflow/plugins/kubernetes/kubernetes_decorator.py

Kubernetes jobs are getting preferred for scheduling on gpu nodes in cases where kubernetes or resources decorator sets `gpu=0` when this should not be the case.
Changes so that gpu vendor is not added to limits if the value is None or zero.

fix: GPU scheduling issue

---

metaflow/_vendor/v3_5/packaging.LICENSE
metaflow/_vendor/v3_5/packaging/__about__.py
metaflow/_vendor/v3_5/packaging/__init__.py
metaflow/_vendor/v3_5/packaging/_compat.py
metaflow/_vendor/v3_5/packaging/_structures.py
metaflow/_vendor/v3_5/packaging/_typing.py
metaflow/_vendor/v3_5/packaging/markers.py
metaflow/_vendor/v3_5/packaging/requirements.py
metaflow/_vendor/v3_5/packaging/specifiers.py
metaflow/_vendor/v3_5/packaging/tags.py
metaflow/_vendor/v3_5/packaging/utils.py
metaflow/_vendor/v3_5/packaging/version.py
metaflow/_vendor/v3_5/pyparsing.LICENSE
metaflow/_vendor/v3_5/pyparsing/__init__.py
metaflow/_vendor/v3_5/pyparsing/actions.py
metaflow/_vendor/v3_5/pyparsing/common.py
metaflow/_vendor/v3_5/pyparsing/core.py
metaflow/_vendor/v3_5/pyparsing/diagram/__init__.py
metaflow/_vendor/v3_5/pyparsing/exceptions.py
metaflow/_vendor/v3_5/pyparsing/helpers.py
metaflow/_vendor/v3_5/pyparsing/results.py
metaflow/_vendor/v3_5/pyparsing/testing.py
metaflow/_vendor/v3_5/pyparsing/unicode.py
metaflow/_vendor/v3_5/pyparsing/util.py
metaflow/_vendor/vendor_v3_5.txt

vendored version of `packaging` does not work for python 3.5 as it contains types. Vendored an older version for the python 3.5 use case

fix: vendor older version of packaging for python 3.5

---

metaflow/plugins/env_escape/client.py

In a Conda environment, it is sometimes necessary to set LD_LIBRARY_PATH to first include the Conda's environment libraries before anything else.
This, however, causes problems with the escape hatch which uses this same modified LD_LIBRARY_PATH *outside* of the Conda environment. This patch fixes this issue by using the convention that, if a Conda environment modifies LD_LIBRARY_PATH, it will save the original LD_LIBRARY_PATH in MF_ORIG_LD_LIBRARY_PATH.

Fix an issue when LD_LIBRARY_PATH is overriden in a Conda environment

---

metaflow/mflog/mflog.py

In case there are borked lines in a log file, the current code would not properly merge the logs because borked lines returned a datetime string as a str and not as bytes like non-borked lines.

Fix the merging of borked lines with MFLOG

---

metaflow/plugins/env_escape/client.py
metaflow/plugins/env_escape/stub.py

The first issue is when subprocesses are created after the main process has activated the environment escape. In this case, multiple processes could try to communicate wit the single escaped server which is a big no no. We explicitly block this from happening now. The case we ran into was an object allocated in a parent being gc in a subprocess.
The second issue relates to the GC which could trigger *while* another communication was happening. This could result in a deadlock since the lock protecting the communication is not reentrant (on purpose). We solve this by preventing the GC from being active during that time.

Fix two possible issues with the environment escape communication

---

metaflow/multicore_utils.py
test/unit/test_multicore_utils.py

This fixes https://github.com/Netflix/metaflow/issues/1316 to optimize the parallel map runs by checking for the first finished process instead of waiting for the first process before checking others.

Check for the first finished parallel proccess

---

metaflow/plugins/airflow/airflow.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/batch/batch.py
metaflow/plugins/kubernetes/kubernetes.py

This will be revisited with a more generalized solution where each individual decorator will be able to set the variables it wants to pass along

Temporary way of passing *some* environment variables to remote nodes

---

metaflow/metaflow_config.py
metaflow/plugins/pypi/conda_environment.py

re-enables the support for extending conda dependencies via overriding `get_pinned_conda_libs` in extensions.
Addresses pending review comment from @romain-intel

chore: enable extending conda deps in new implementation

---

metaflow/plugins/argo/argo_client.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_cli.py

Adds a command for listing Argo workflow templates
`python testflow.py argo-workflows list-templates`
will list all workflow templates that have the same flow name as testflow.py. These will include all projects using the flow, production deployments, non-project deployments etc.
`python testflow.py argo-workflows list-templates --all`
will remove scoping to the flow file from the command and return a complete list of workflow templates
TODO: the API call for listing the objects needs consideration. Presumably the amount of objects even for large organisations shouldn't be extremely massive, as this is fetching workflow templates, and not workflows. Nevertheless some caution here, possibly requiring pagination in the future.

feature: add list-templates command for argo workflows

---

metaflow/plugins/cards/card_modules/convert_to_native_type.py

#1344 added logic for displaying more types, including unknown types, when rendering `pandas.DataFrame` objects on the default card. However, it only addressed rendering of column values, not indexes. This PR applies the same parsing logic to DataFrame indices as to the columns.
Here is a lightly modified version of the example flow from #1344 which adds an artifact with a multi-index to check rendering of indices.
```python
from metaflow import FlowSpec, step, Parameter, IncludeFile, catch, card
import math, time, uuid, datetime, random, string, sys
from decimal import Decimal
import requests
class CustomClass():
def __str__(self):
return 'a' * int(1024**2)
def __repr__(self):
return str(self)
class DefaultCardFlow(FlowSpec):
str_param = Parameter('str_param', default='刺身は美味しい') …
```

Safely parse `pandas.DataFrame` indexes for default card

---

metaflow/plugins/cards/card_modules/convert_to_native_type.py

The default card formats timezones in dataframes with `time_format = "%Y-%m-%dT%H:%M:%SZ"`. This should be `time_format = "%Y-%m-%dT%H:%M:%S%Z"`; without the % before the Z the formatted time will end with the literal Z, which means UTC time.

fix timezone in default card time format string

---

metaflow/parameters.py
metaflow/plugins/argo/argo_workflows.py

This PR adds information on which parameters are required, to the annotations section of argo-workflow templates.  This can be used to validate the well-formed-ness of workflow submissions before submitting the workflow to argo-workflows.  Before this PR the only way to validate parameters was to submit the workflow and wait until metaflow runs within the argo-workflow, only to fail at parameter validation.  After this change, we can fail-fast and, in the process, save on compute as well as etcd storage.
Manually tested for the following parameter types both locally and in argo-workflows:

Add parameter info to argo workflow template annotations

---

metaflow/plugins/aws/batch/batch_client.py
metaflow/plugins/aws/step_functions/step_functions.py

fixes the use of `shared_memory` and `use_tmpfs` in combination with a resources decorator for step-functions.
closes #1609

fix: resource decorator step functions issue

---

metaflow/plugins/argo/argo_workflows_cli.py

group some of the fail-state statuses of Argo Workflows together to have a more coherent output across different environments.

feature: add status grouping to argo-workflows output

---

metaflow/plugins/aws/aws_utils.py

Changes the way `BatchDecorator` pulls values from `ResourcesDecorator` if any are set. This limits the values to only ones supported through `resource_defaults` in batchdeco.
Should unblock #1500 which currently breaks for batch as it introduces a `disk=` attribute which is not supported for the batch deco, yet gets pulled in by the current implementation.

fix: apply only supported attributes from resources decorator in batch

---

.github/workflows/test.yml
metaflow/__init__.py
metaflow/extension_support/__init__.py
metaflow/metadata/util.py
metaflow/metaflow_config.py
metaflow/multicore_utils.py
metaflow/plugins/argo/argo_workflows_cli.py
metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/plugins/metadata/__init__.py
metaflow/plugins/metadata/service.py
metaflow/util.py
metaflow/version.py
setup.py
version.py

Also improve performance by removing pkg_resources and replacing with another way of getting the package version.
Finally, remove spurious includes that have no business being there :)

Remove use of distutils from code (not setup.py yet)

---

metaflow/plugins/kubernetes/kubernetes.py

Fixes #1554 
When running large for-each branches (3000+) Metaflow will sometimes cause job name collisions on kubernetes. This adds a UUID to the prefix which should add sufficient entropy to prevent this from happening.

Add a uid for the kubernetes job creation

---

metaflow/plugins/pypi/pip.py

add support to pypi for custom index in pip config.
This also enables private indices that require authentication, as the user:token can be part of the config, which is only required during solving of the environment (dev machine) and not after it is cached.
tested to work with private AWS CodeArtifact with upstream pypi.

feature: support custom index config for pypi decorator

---

metaflow/plugins/resources_decorator.py

We would like to use the @resources decorator instead of @kubernetes to specify resource requirements for our job so we can run flows locally or on Kubernetes by using `--with kubernetes` instead of modifying the code. The @resources decorator only supports cpu, gpu, memory and shared_memory at the moment.
This PR just adds the disk parameter. Default value (10240mb) is the same as the one in @kubernetes.

Adding 'disk' parameter to @resources decorator

---

metaflow/plugins/cards/card_modules/convert_to_native_type.py

Currently, the default card passes null values in `pandas` dataframes to the frontend as `NaN` which is not a valid JSON value. This results in the card failing to render in the browser. This PR fills null values with `null`, which is valid JSON.
I have tested this fix with the following flow (lightly modified from the test flow in #1344  to include a few null values)
```python
from metaflow import FlowSpec, step, Parameter, IncludeFile, catch, card
import math, time, uuid, datetime, random, string, sys
from decimal import Decimal
import requests
class CustomClass():
def __str__(self):
return 'a' * int(1024**2)
def __repr__(self):
return str(self)
class DefaultCardFlow(FlowSpec):
str_param = Parameter('str_param', default='刺身は美味しい')
file_param = IncludeFile('file_param')
json_param = …
```

fix nulls in pandas columns on default cards

---

metaflow/plugins/metadata/service.py

Some leftovers from #1585 that went unnoticed.
This might have had an effect on object access through the client library, noticed issues with the Metaflow-UI log access at least when building with the latest client library included.

fix: remove leftover use of LooseVersion

---

metaflow/tracing/__init__.py

output the exception info to stderr instead of stdout.
also closes #1620

fix: output ImportError for tracing module to stderr

---

metaflow/metaflow_config.py
metaflow/tracing/__init__.py

add `METAFLOW_DEBUG_TRACING` environment variable flag and silence tracing ImportErrors by default.

feature: add debug_tracing flag

---

metaflow/plugins/pypi/pypi_decorator.py

fixes logic introduced in #1595 which incorrectly evaluates any `@pypi` environment as disabled.
tested with
```python
from metaflow import step, FlowSpec, pypi, pypi_base, conda, conda_base
class EnvTest(FlowSpec):
@pypi
@step
print("Starting 👋")
import sys
print(sys.executable)
print(sys.path)
@step
def end(self):
print("Done! 🏁")
EnvTest()
```
which should include the micromamba environment and Python executable (before this PR it would only point to the host Python)
Resolves #1605

fix: pypi environment issues

---

metaflow/plugins/argo/argo_workflows.py

This can be used by downstream automation to determine when the flow was last updated in argo-workflows
Sample workflow template snippet YAML:
```yaml
annotations:
metaflow/flow_name: AHelloFlow
metaflow/owner: rohan.outerbounds@gmail.com
metaflow/production_token: ahelloflow-0-qpdi
metaflow/latest_deployment: '2023-11-14T02:47:54.202588+00:00'
metaflow/user: argo-workflows
```

Add deployed-at timestamp in annotations for argo-workflows

---

metaflow/plugins/pypi/pip.py

Adds support for the pip config environment variable `PIP_INDEX_URL`
Reworks the way pip config is treated in order to get around issue https://github.com/pypa/pip/issues/11700 where using `PIP_CONFIG_FILE` does not play well with `pip config get`

fix: pip config issues with pypi decorator

---

metaflow/plugins/airflow/airflow_cli.py
metaflow/plugins/argo/argo_workflows_cli.py
metaflow/plugins/aws/step_functions/step_functions_cli.py

fix deprecation warnings due to escape characters in some of the regex patterns being used, by changing these to raw strings.

fix: change regex patterns to raw strings

---

metaflow/plugins/env_escape/client.py
metaflow/plugins/env_escape/client_modules.py
metaflow/plugins/env_escape/server.py
metaflow/plugins/env_escape/utils.py

We were not properly creating all the aliased classes in the conda environment (only creating the "canonical" one (which is the first one listed in the server_mappings.py file).
Similarly, the hierarchy of exceptions was not properly created in all cases.

Fix an issue with aliases in environment escape server mappings.

---

metaflow/plugins/cards/card_modules/convert_to_native_type.py

The default card currently fails to render for a run that has an artifact which is a DataFrame with 0 rows and at least 1 string column or index level. The failure arises because `x.astype("string").str.len().max()` returns null when `x` has length zero.
Here is a trial pipeline:
```python
from metaflow import FlowSpec, step, Parameter, IncludeFile, catch, card
import math, time, uuid, datetime, random, string, sys
from decimal import Decimal
import requests
class CustomClass():
def __str__(self):
return 'a' * int(1024**2)
def __repr__(self):
return str(self)
class DefaultCardFlow(FlowSpec):
str_param = Parameter('str_param', default='刺身は美味しい')
file_param = IncludeFile('file_param')
json_param = Parameter('json_param', default='{"states": {[{"CA", 0}, {"NY", 1}]}')
float_param = …
```

fix rendering of zero-length DataFrames in default card

---

metaflow/plugins/pypi/conda_environment.py
metaflow/plugins/pypi/pip.py
metaflow/plugins/pypi/utils.py

Fixes issues with packages/versions having characteres requiring url encoding.
Closes #1642

fix: pypi decorator handling packages with special characters

---

metaflow/plugins/pypi/conda_environment.py

Fixes issue where conda environments are wrongly treated as disabled if the decorator is implicitly applied.
The underlying reason is that due to the lifecycle of decorators, the `disabled` attribute gets cast to string early enough, that the `is_disabled` check fails.
Can test this by slapping the following at the end of `step_init` in conda decorator
```python
print(f"has conda decorator: {step} - disabled: {self.disabled} - type: {type(self.disabled)}")
``` 
closes #1667

fix: conda environment counts as disabled with implicit decorator

---

metaflow/task.py

separate the `task_pre_step` and `task_decorate` in order to support better setup-order of dependent decorators.
Specifically we want the `PATH` patching of conda-decorator to happen early so that other decorators can rely on this *after* `task_pre_step` in the lifecycle.

fix: decorator init order

---

metaflow/plugins/cards/card_cli.py
metaflow/plugins/cards/card_creator.py
metaflow/plugins/cards/card_modules/components.py
metaflow/plugins/cards/card_modules/test_cards.py
metaflow/plugins/cards/card_server.py
metaflow/plugins/cards/component_serializer.py

- Added a `sync` argument to the card creator
Lets assume the case that the user is only doing `current.card.append` followed by `refresh`. In this case, there will be no process executed in `refresh` mode since only the `layout_has_changed` will always be true and we will keep running `render_runtime` instead of any `refresh` call. As a result, there will be no data update that informs the UI of the `METAFLOW_RELOAD_TOKEN` change. In the meantime the UI will be trying to seek for the data update object but it will constantly find None. Due to this the card Iframe will not reload and keep being in it's initial state.
This change ensures that after the first `render_runtime`, any time a `render_runtime` is called, we follow it up with a subsequent SYNCHRONOUS `refresh` call. This will …

[@card] [card-core] always call `refresh` after first `render_runtime` (5/N)

---

metaflow/plugins/cards/card_cli.py
metaflow/plugins/cards/card_creator.py
metaflow/plugins/cards/card_modules/components.py
metaflow/plugins/cards/card_modules/test_cards.py
metaflow/plugins/cards/card_server.py
metaflow/plugins/cards/card_viewer/viewer.html
metaflow/plugins/cards/component_serializer.py

- Modified card datastore to accomodate retrieval of runtime data updates
- Added a card viewer html file
- Created a simple HTTP based card server that will help showcase the realtime cards from querying the server
- Card datastore's read and write path retrieval methods now explicitly are given the suffix they retrieve from. We do this because the suffix determines if we are extracting a card or a data update
- Added a private method in the `Card` (user-interface) to get the data related to a card.

[@card] Realtime cards (4/N)

---

metaflow/cards.py
metaflow/plugins/cards/card_cli.py
metaflow/plugins/cards/card_creator.py
metaflow/plugins/cards/card_modules/base.html
metaflow/plugins/cards/card_modules/basic.py
metaflow/plugins/cards/card_modules/components.py
metaflow/plugins/cards/card_modules/convert_to_native_type.py
metaflow/plugins/cards/card_modules/test_cards.py
metaflow/plugins/cards/card_server.py
metaflow/plugins/cards/card_viewer/viewer.html
metaflow/plugins/cards/component_serializer.py

- Markdown and Artifact Component support real-time updates.
- default/blank cards support real-time update
- Vega Charts And Progress Bar support in Python Land

[@card] Realtime cards (3/N) 

---

MANIFEST.in
metaflow/plugins/cards/card_modules/basic.py
metaflow/plugins/cards/card_modules/components.py

add viewer HTML file into manifests
Update function also supports providing Altair chart. 
- Fixed Docstring for the Progressbar  
- Added docstring to VegaChart update function
- If a markdown component contains a paragraph then `svelte-markdown` doesn't end up rendering appropriately during data update calls. It renders empty `<p>` tags.
- Adding a new line at the start of markdown text will ensure all markdown which contains paragraphs is rendered correctly during data update calls.

[realtime-card] pre-release bug Fixes. 

---

metaflow/version.py

Doing a minor jump in semver because this will mark the official version from which dynamic cards will be supported

bump Metaflow version

---

metaflow/flowspec.py
metaflow/parameters.py
setup.cfg
test_runner
tox.ini

Suggested changes on top of the work of @maxzheng on https://github.com/Netflix/metaflow/pull/1653

Set parameters for running flow instead of any imported

---

metaflow/flowspec.py
metaflow/metaflow_config.py
metaflow/runtime.py
metaflow/task.py
metaflow/util.py

In this change, we
1. add values of foreach items to flowspec for convenient access to values in foreach steps. 
2. Update foreach stack to include value.
3. Add formatted foreach stack (path from root to current level) to metadata, guarded by a flag.
Currently,  we try to get "value" of the for each in the following order:
1. If the item is list of primitive types like `["a", "b", "c"]`, we will use the literal value directly
2. Otherwise, we use replib to get a serialized value of the iterable, limited to 30 charactors.
The end result will be of the form `[value]`.  We will then
1. Use the list of value (generated in a split/parent node) in the `task_finish` function inside a custom decorator.  
2. Use the list of value when constructing foreach stack, which will eventually be used to …

[Ready for Review] Support more convenient foreach variable/value search-ability.

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/plugins/aws/step_functions/step_functions_client.py

This PR should over-ride https://github.com/Netflix/metaflow/pull/1596
Usage:
`python flow.py step-functions terminate sfn-d41004cd-1bbf-4c25-b284-94bfc921d78b`

add ability to terminate execution of a step-fn state machine

---

metaflow/plugins/aws/batch/batch_client.py

When `@batch` contains both `inferentia` and `efa` arguments, the list of `/dev/neuron{N}` (for inferentia and trainium) specifications in `nodeProperties.nodeRangeProperties.container.linuxParameters.devices` are currently being overwritten by the list of  `/dev/infiniband/uverbs{N}` (for efa eni's) devices.

fix overwrite of neuron devices when efa devices are also specified

---

metaflow/parameters.py

Closes https://github.com/Netflix/metaflow/issues/1712
This is how it looks

add __repr__ and __str__ methods to Parameter

---

metaflow/plugins/aws/batch/batch.py

adds `METAFLOW_OTEL_ENDPOINT` to the Batch environment so openetelemetry can be enabled correctly when executing remotely on Batch/Step Functions.
closes #1746

fix: add otel endpoint to batch env

---

metaflow/flowspec.py
metaflow/metaflow_config.py

Add a length control for final result as string. This will prevent us from generating a list of foreach value with crazy long value.

[Ready for review] Add explicit max length control for foreach value.

---

metaflow/flowspec.py

`_foreach_values` is now stored as artifacts for each step but this is not intended for users to consume. In merge artifacts, however, we will try to merge them by default, which could fail if the foreach are dynamic. This PR will make merge artifacts skip the foreach value (at join step). This foreach value will have no meaning after joining anyways, so there should be no impact to the entire flow.

[Ready for review] Ignore _foreach_values in merge artifacts

---

metaflow/plugins/argo/argo_workflows.py

Adds more details to the slack webhook alerts sent when using `--notify-on-error` or `--notify-on-success` using [Slack's block kit](https://api.slack.com/block-kit) as part of the argo workflow template creation
Before the messages would simply be:
> :rotating_light: TestFlow/argo-testflow-z7mtw failed!
Now they include a link to the UI and conditionally add `@project` metadata when available, e.g. triggering an argo workflow created from the following:
```
from metaflow import FlowSpec, project, step
@project(name="test")
class TestFlow(FlowSpec):
@step
@step
def end(self):
pass
TestFlow()
```

add alert details using slack block kit

---

metaflow/parameters.py

updated list of reserved parameter names.
closes #1735

fix: update list of reserved parameter names

---

metaflow/package.py

allow files that start with . to be added via `--package-suffixes`
closes #1741

fix: allow dot files with `--package-suffixes`

---

metaflow/metaflow_config.py
metaflow/plugins/datatools/s3/s3op.py

No-op to current behavior, but configuration on S3 parallel process count at top level.

[Ready for review] make default s3 worker count configurable

---

metaflow/sidecar/sidecar.py
metaflow/sidecar/sidecar_subprocess.py

Current send_msg is not threadsafe. This PR add an optional to use lock that guards the shared ressource (stdin of the subprocess).

[Ready for review] add an option to make sidecar send msg func threadsafe

---

metaflow/cli.py
metaflow/datastore/task_datastore.py
metaflow/runtime.py
metaflow/task.py

Current clone-only resume has a few flaws we need to solve:
1. Each task to be resume will create a resume runtime and they all want to resume the previously completed execution tree in topological order. This resulted in unnecessary competition between resume tasks.
2. If one resume wins the race (registered new task id) but never completed the cloning, the future attempts will never run and the resume will never finish.
To tackle this, we decided to elect a resume leader (whichever tasks register _parameters task first) and also remembers the resume leader path. All non-leader will need to wait for the leader to finish resuming (which essentially is copying the datastore pointer to new place).
In the case of a failed clone, we will check whether task_id is registered and task is …

[Ready for review] Make Clone-only resume more efficient.

---

metaflow/plugins/aws/batch/batch.py
metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/batch/batch_client.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/aws/step_functions/step_functions.py

We can now do the following:
- This can expect a list where each string in the list follows `key:value`
```
@batch(log_options=["awslogs-group:try/batch/custom/demo"])
@step
def mid(self):
print("yayyyy")
```
or perhaps just a single string of the form `key:value`
```
@batch(log_options="awslogs-group:try/batch/custom/demo")
@step
def mid(self):
print("yayyyy")
```
Of course the assumption is that the log group `try/batch/custom/demo` should exist first on Cloudwatch...

ability to customise log driver and log options

---

metaflow/plugins/env_escape/client.py

When a function was unpickled, the name did not match what was expected.

Fix an issue when unpickling functions through the escape hatch

---

metaflow/plugins/aws/batch/batch_client.py

Closes https://github.com/Netflix/metaflow/issues/1776
If nothing is supplied... it defaults to the previous behaviour and should thus automatically set the correct `log driver` and `log options`

fix log options

---

metaflow/metaflow_config.py
metaflow/plugins/pypi/conda_environment.py
metaflow/plugins/pypi/pip.py

Closes https://github.com/Netflix/metaflow/issues/1658
Present https://anaconda.org/conda-forge/keyrings.google-artifactregistry-auth
and on https://pypi.org/project/keyrings.google-artifactregistry-auth/

inject keyrings.google-artifactregistry-auth for private GCP PyPi registry

---

metaflow/plugins/pypi/conda_environment.py
metaflow/plugins/pypi/pip.py

Reverts Netflix/metaflow#1772 for now since we might wanna discuss on the disabling of `--no-input` further...

Revert "inject keyrings.google-artifactregistry-auth for private GCP PyPi registry"

---

metaflow/plugins/pypi/pip.py

add support for `#subdirectory=` as part of a pypi package version.

fix: support specifying subdirectory with PyPI vcs sources.

---

metaflow/plugins/aws/batch/batch_client.py

Reason: a click option that has `default` as `None` and `multiple` as `True` gives an empty tuple i.e. `()` when the option is not supplied, which is weird, thus the issue

check for falsy values instead of just None

---

.github/workflows/metaflow.s3_tests.yml

We are replacing `pull_request_target` because it could be triggered automatically against untrusted PRs allowing malicious actors to run code and exfiltrate secrets.  Replacing it with `pull_request` could solve the issue.
More in this article: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

[Ready for review] replace pull_request_target

---

metaflow/decorators.py

- When we expose flow decorator options with a `-` in the name, the code crashes at setting `deco_flow_init_options` with a KeyError on `deco_options`. The `deco_options` as passed down from Click which converts any `option` with `-` to `_`.
- translating the `-` to `_` ensures the `option` can match the value in `deco_options` and doesn't result in KeyError. This is only the case **when options contain `-`**
- Already present flow decorators will have no issues anyways since this only effects flow deco options that have a `-` in the name (which currently none of them do).
- This doesn't handle the case where option names have `_`. But opens up creation of options with `-`'s.

[bug fix] Flow decorator click option names fix

---

metaflow/plugins/aws/aws_utils.py

Right now, getting EC2 metadata is silently broken for IMDSv2. The APIs are the same, except IMDSv2 requires a token before calling the "metadata" API.
This PR adds support for getting the IMDSv2 token, and falls back to using no token if it isn't available.

Add support for getting EC2 metadata through IMDSv2.

---

metaflow/plugins/aws/aws_utils.py

A fix for https://github.com/Netflix/metaflow/pull/1808.. After merging, realized that this'll break IMDSv1, since token will always be undefined and raise. This fixes that issue.

Initialize token for IMDSv1 ec2-metadata

---

.github/workflows/test-stubs.yml
.github/workflows/test.yml

fixes specifically to tests relying on `macos-latest`
cause of issues being https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
where the latest runner image has switched to macos 14, and arm64, bringing with it a lot of breaking changes for the CI. Most notably dropping support for older Python versions that we were testing for.

fix: github tests

---

.github/workflows/test.yml

swap R tests to run on ubuntu due to macos-latest issues

fix: R tests

---

metaflow/metaflow_config.py
metaflow/plugins/env_escape/__init__.py

We print a warning if a package is supposed to be escaped but not (e.g. User include the package in conda environment). However, the log may later disturb s3op wokers since the communication between subprocesses is depend on stdout.
For example:
1. `bdp-boto` is suppposed to be escaped
2. User specify a version of `bdp-boto` in their conda environment
3. We print out "Not using environment escape for 'bdp_boto' as module present"
5. User do a `S3.put_many()`
6. The s3 option would fail since it doesn't understand the log "Not using....."
```
File "/root/metaflow/metaflow/plugins/datatools/s3/s3.py", line 1561, in _update_out_lines
>      out_lines[int(idx.decode(encoding="utf-8"))] = rest
>  ValueError: invalid literal for int() with base 10: 'Not'
```
Thus, we add a flag to control …

Add a flag to control escape hatch log

---

metaflow/plugins/aws/step_functions/step_functions.py

Since April 30th, 2024, I've encountered a recurring error when creating/updating a state machine for Metaflow orchestration, particularly under the `--use-distributed-map` functionality. Recent changes to AWS API validation for state machine definitions have introduced more stringent checks before a state machine is created, as detailed in the [AWS changelog](https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#L71).
The issue stems from the item_reader component improperly parsing JSON parameters due to a syntax error in the specified JSON Key path. This problem was not previously detected because there were no ValidateStateMachineDefinition checks in place. The original line causing the error in JSON was:
[.parameter("Key.$", "$.Body.ResultFiles.SUCCEEDED.[0].Key") …

Fix: JSON Reference Path Error in AWS Step Functions Distributed Map

---

metaflow/plugins/aws/batch/batch_cli.py

addresses: https://github.com/Netflix/metaflow/issues/1771
issue:
`python hello.py batch step --help` command was breaking due to wrong type for click.Choice arg.
change:
setting default arg for `ubf-context` from None to "none" in "batch step" make it compatible with [click.Choice()](https://github.com/mae5357/metaflow/blob/4e648627ea6eb6535c0e28e80ce4daf8f1839ee7/metaflow/_vendor/click/types.py#L137-L138) 
however, ubf-context is not needed for the "step" function when using aws-batch, so we can safely remove altogether.

bug fix: unused arg for batch step --help

---

metaflow/clone_util.py

This `attempt_ok` attribute is not used within metaflow runtime but is needed for UI to correctly display the status of a node. For example, in metaflow-service repo [here](https://github.com/Netflix/metaflow-service/blob/e0b149996020f1e613863015ffffee247cce49f3/services/ui_backend_service/data/db/tables/task.py#L177), if `attempt_ok` is not set, then the status become unknown.
For example, like this:

[Ready for Review] add attempt_ok flag so that UI will not show up unknown node

---

metaflow/metaflow_config.py
metaflow/metaflow_environment.py
metaflow/plugins/__init__.py
metaflow/plugins/airflow/airflow.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/azure/azure_exceptions.py
metaflow/plugins/azure/azure_secret_manager_secrets_provider.py
metaflow/plugins/kubernetes/kubernetes.py

* Adds secret backend support for Azure Key Vault. Details about the Azure Key Vault integration are documented @ https://docs.google.com/document/d/1QLISgiueZamA70WgIdKKVFOLqBmqGopuEBtXQyjfQLk/edit?usp=sharing
* Corresponding PR to update the metaflow docs is https://github.com/Netflix/metaflow-docs/pull/125
* Tested against Azure Key Vault

Secret Backend Support for Azure Key Vault

---

metaflow/metaflow_config.py

* In order to support azure key vault for @secrets, we used the 4.8.0 az-keyvault-secrets library. However this conflicts with the azure-cli package which is still dependent on the 4.7.0 az-keyvault-secrets
[Darwin](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Darwin.txt#L19)
[Linux](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Linux.txt#L19)
[Windows](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.windows.txt#L19)
Without this PR - installing metaflow + azure-cli will conflict with each other. The Integration of az-key-vault works as intended with 4.7.0 as well. 
Hence this PR is not going to cause any unintended consequences.

reducing the dep version to 4.7.0 (#47)

---

metaflow/plugins/argo/argo_workflows.py

In order to display cron information in the deployments UI - we will add the cron information in the Workflow Template annotation. The UI can then use this information and display it.
Annotations added are:
metaflow/cron: {'schedule': <CRON>, 'tz':<timezone>}
They show up only when a @schedule decorator is used.
##How is this tested?
If timezone is defined:
If timezone is not defined:

[OB-625] adding metaflow/cron annotation to argo workflows

---

metaflow/__init__.py
metaflow/runner/metaflow_runner.py
metaflow/runner/nbrun.py
metaflow/runner/subprocess_manager.py

Should only be merged after https://github.com/Netflix/metaflow/pull/1732
This allows us to do stuff like:
```
runner = Runner('../try.py', metadata="local")
result = runner.run(alpha=5, tags=["abc", "def"], max_workers=5)
while not result.run.finished:
print('trying again...')
result = runner.resume()
```
Also allows us to use `run` inside environments which already have a running event loop such as Jupyter notebooks.

synchronous run and resume functionality + nbrun for runner API

---

metaflow/runner/metaflow_runner.py
metaflow/runner/nbrun.py

so user can clean up results without context managers

add explicit cleanup() methods in Runners

---

metaflow/plugins/argo/argo_workflows.py

This fixes issue #1870.
I did not find any test setup to create unit or integration tests. So my only test was replacing the Metaflow library with my fork and ensuring the sensors would be deleted. Before the change, they were not. 
Here are the logs for the same flow used in the issue description. As expected, this time the sensors were deleted. I have also checked the Kubernetes resources.
* `argo-workflows delete`
```
Metaflow 2.12.0 executing MyTestFlow for user:g.pereira.3
Project: my_test_project, Branch: user.g.pereira.3
Validating your flow...
The graph looks good!
Running pylint...
Pylint not found, so extra checks are disabled.
Deleting workflow mytestproject.user.g.pereira.3.mytestflow...
Deleting sensor mytestproject.user.g.pereira.3.mytestflow...
Deleting Kubernetes resources …
```

bugfix: properly deletes Argo Events trigger sensors when @project is used

---

metaflow/plugins/env_escape/stub.py

For returned exceptions, we now raise an AttributeError instead of a RuntimeError when an attribute is accessed. This allows things like `getattr(obj, "foo", default)` to work better.

Fix escape hatch to make __getattr__ behavior more standard

---

metaflow/R.py
metaflow/decorators.py
metaflow/flowspec.py
metaflow/parameters.py
metaflow/plugins/airflow/airflow.py
metaflow/plugins/airflow/sensors/base_sensor.py
metaflow/plugins/airflow/sensors/external_task_sensor.py
metaflow/plugins/airflow/sensors/s3_sensor.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/step_functions/step_functions.py
metaflow/runner/click_api.py
metaflow/runner/metaflow_runner.py
metaflow/runtime.py

This scopes decorators and parameters to the flow itself which should improve compatibility with the runner

Remove global nature of parameters and flow decorators

---

metaflow/cli.py
metaflow/plugins/pypi/conda_environment.py

to get output of the nature of

add timestamps to conda debug logs

---

metaflow/plugins/pypi/conda_environment.py

use deepcopy for get_environment instead to avoid modifying deco attributes

fix: decorator attributes being modified in get_environment

---

metaflow/plugins/cards/card_cli.py
metaflow/plugins/cards/card_modules/basic.py

- Error cards didn't contain a reload token replacement because of which the UI keeps trying to poll for new cards.
- This is not the best situation because the UI will keep refreshing the card constantly until the UI catches hold of the card.
- The UI changes will obviously follow for situations where a data update might be published but a card doesn't end up getting saved because of some data store issue; This PR will fix the bug and ensures that if a error card gets created instead of an expected card then the UI still gets the right reload token.

[cards] bug fix with error card renders

---

metaflow/plugins/argo/argo_workflows.py

Changes to never use zlib compression for long static input-paths for argo-workflows, as this breaks the template value substitution for input-paths.

fix: long names with static split fails join step on Argo Workflows

---

metaflow/metaflow_config.py
metaflow/plugins/pypi/conda_decorator.py
metaflow/plugins/pypi/conda_environment.py
metaflow/plugins/pypi/pypi_decorator.py

We need some additional extension capabilities to be able to implement #1796 as an extension, these being:
- add 'docker' to list of supported environments for `@conda` and `@pypi`
- ability to **fallback** to the core Conda environment initialization for a subset of steps only.
Note: the changes to `conda_environment.py` would at the moment result in any plugin relying on the new `only_steps=` to break with the bleeding edge nflx-extension conda implementation

feature: Conda env extension hooks

---

metaflow/plugins/argo/argo_workflows.py

do not unnecessarily escape html characters in argo events payload.

fix: do not escape html in Argo Events payload

---

metaflow/cli.py
metaflow/system/__init__.py
metaflow/system/system_logger.py
metaflow/system/system_monitor.py
metaflow/system/system_utils.py
metaflow/task.py

Currently, users don't have the ability to use their implementation of logger and monitor sidecars in their own code. Additionally, if platform developers want to instrument their Metaflow extensions, they have to pass in the logger/monitor constructs to each one of their plugins, leading to code duplication.
This PR exposes two new singleton objects called `_system_logger` and `_system_monitor` that can be used to access the monitor and the logger anywhere.  
- The monitor/logger can be accessed both within and outside a Metaflow flow. This allows us to instrument Metaflow plugins like `metaflow.S3`, which is often used outside of a flow as well. 
The monitor/logger sidecar can be used in the following manner:
```python
with _system_monitor.count("<your_metric_name>"): 
pass …
```

Expose metaflow logger and monitor via singleton

---

.github/workflows/metaflow.s3_tests.yml

py < 3.8 is no longer available on stock GHA for MacOS

remove old py versions for s3 tests

---

metaflow/lint.py
metaflow/metaflow_current.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/parallel_decorator.py
metaflow/plugins/test_unbounded_foreach_decorator.py
metaflow/runtime.py

- fix tests for ubf based on new changes to core.
- [feedback] register metadata in parallel decorator
- [feedback]@parallel inject in current: - move `current.parallel` from `metaflow_current` to `parallel_decorator`
- [feedback] appropariately setting task-metadata for parallel stuff - The 'world size' metadata will be set in the @parallel decorator. - The 'node-index' metadata, however, varies depending on the type of computing environment executing the task so it will be set in the appropriate compute decorators. - One reason to specify 'node-index' within compute decorators is that the parallel implementation in the compute decorator might not directly set the required environment variables (`MF_PARALLEL_*`). Instead, these values may be established during the `task_pre_step` phase …

[parallel-fixes] core + test changes

---

metaflow/plugins/kubernetes/kubernetes.py
metaflow/plugins/kubernetes/kubernetes_cli.py
metaflow/plugins/kubernetes/kubernetes_client.py
metaflow/plugins/kubernetes/kubernetes_decorator.py
metaflow/plugins/kubernetes/kubernetes_job.py
metaflow/plugins/kubernetes/kubernetes_jobsets.py

- Some changes stemming from Netflix/metaflow#1854
- reorder imports
- changes to env var prefixes + id generation
- Abstraction over Jobset Spec
- Create general abstraction and copy style of how we create jobspec for native k8s jobs.
- simplified the implementation.
- similar pattern/trend to follow for argo
- remove older implementation
- @parallel metadata from k8s decorator - added attempt to MetaDatum tags - We didn't have this earlier

[refactor-jobsets] refactor to new implementation

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_decorator.py
metaflow/plugins/argo/jobset_input_paths.py
metaflow/plugins/kubernetes/kubernetes.py
metaflow/plugins/kubernetes/kubernetes_jobsets.py

> supported :
- foreach + parallel
- parallel with Argo
- dynamically set worker-counts.
- should work with @timeout / @project /@card etc.
- retries working with native Argo
- fully self contained jobset with argo support - Requires Jobset v0.6.0 [kubernetes-sigs/jobset#523]
> not-supported:
- support for catch
> Notes
- not using the `{{retries}}` like we do in container templates
- Instead passing down {{retries}} as a `inputs.parameters` which will be accessible in the Jobset manifest.
- Temporary tweek to boto dep to ensure that boto install failures dont fail deployment.
- instead of relying on the kubernetes object, we freshly create a object in the ArgoContainer templates.
- Code in the same style as the kubernetes/argo integrations with explicit filling of variables and decoupled …

[argo] support for @parallel

---

metaflow/flowspec.py

- When users call `self.merge_artifacts` for a join step in a UBF, the `_unbounded_foreach` internal variable gets merged too. This is because it's not included in the `INTERNAL_ARTIFACTS_SET` that exclude it in the merge_artifacts function.
- This doesn't become a problem unless users have a complex graph where there are branches and UBFs within the branches.
- but in cases where there are branches and users are calling `merge_artifacts`, then the `_unbounded_foreach` variable gets propagated to further join steps causing the code to crash in the local runtime with the join step. 
- this only affects local runtime and everything seems to work fine with remote schedulers.
- Adding this variable to the `INTERNAL_ARTIFACTS_SET` fixes the problem.

[ubf] bug fix when using `merge_artifacts` in UBF joins

---

metaflow/cli.py
metaflow/clone_util.py
metaflow/runtime.py

Extend the resume speedup change to native(local) resume.
Note:
* We will go over all the successful tasks and copy them first. Then we reconstruct runtime queue to continue.
* We will keep UBF resume behavior the same. i.e if some mapper tasks fail, all mapper tasks will reran in the resume.
A few test example flows:
* Resume w/ some branch: [link](https://gist.github.com/darinyu/b895a8aca64f4674a147475763a50a85)
* Resume during failure on foreach split :[link](https://gist.github.com/darinyu/5ca42e7bad8e984f6bff942e1f064ff4)
* Resume during failure on UBF split: [link](https://gist.github.com/darinyu/aaf604a9e1e22c51c958135974caa27a)
* Resume during failure on UBF join: [link](https://gist.github.com/darinyu/1393a506b77b874c0cffeadaac2bfb5d)
To test the above flows:
```python
python …
```

[Ready for Review] Improve native resume 

---

metaflow/metaflow_config.py
metaflow/metaflow_config_funcs.py

This allows a per-project (directory) override of configuration values.
This is similar to using profiles but allows for finer grained overrides and will be particularly useful with default decorators.

Add local configuration option

---

metaflow/flowspec.py
metaflow/graph.py
metaflow/util.py

_graph_info could contain non POD which broke things particularly in the presence of extensions

Fix an issue with _graph_info

---

metaflow/cli.py
metaflow/graph.py
metaflow/runtime.py
test/core/metaflow_test/formatter.py
test/core/run_tests.py
test/core/tests/resume_succeeded_step.py

when running resume with `python flow.py resume {step_name}`, user may want to rerun the "step" and continue with the execution. In current code, we will blindly copy everything as long as the step was successful.
The proposed change will look at step in topological order and skip cloning the ones on and after the specified steps (and then rerun everything if possible).

[Ready for Review] Fix issue where resuming on successful run will fail.

---

metaflow/plugins/kubernetes/kubernetes_decorator.py

fixes issue with launching kubernetes tasks with a default node_selector. Introduced in #1952 
is the `else` block required at all? the default dict messes up with the value of node_selector being passed to the CLI, where parsing fails.
```
2024-08-19 12:06:18.037 [1450/start/4611 (pid 74904)] in kube-cli step the node_selector is: {}
2024-08-19 12:06:19.178 [1450/start/4611 (pid 74904)] Kubernetes error:
2024-08-19 12:06:19.178 [1450/start/4611 (pid 74904)] Unable to parse kubernetes list: {}
```

fix: passing kubernetes compute pool option

---

metaflow/metaflow_environment.py
metaflow/plugins/aws/aws_utils.py

gets rid of awscli as a dependency, opting to instead use boto3 directly with inline python to download the codepackage. Supersedes #1778 
also introduces an environment variable to allow skipping installing bootstrap dependencies completely. Motivated by #1957

feature: better bootstrap dependencies

---

metaflow/client/core.py

Python's custom attribute access protocol requires `AttributeError` to be raised on access failure ([docs link](https://docs.python.org/3.10/reference/datamodel.html#object.__getattr__)). The current implement propagates `KeyError` from `dict`, which breaks `hasattr()` operations on `MetaflowData`.
This PR checks for key existence and raise the correct exception in `MetaflowData.__getattr__`.
Fixes #1970.

fix(MetaflowData): Raise AttributeError on failed `__getattr__` access

---

metaflow/metaflow_environment.py

fixes edge case where setting `METAFLOW_S3_ENDPOINT_URL` to an empty value would break the new bootstrapping script

fix: deal with empty string and None values in s3 endpoint_url

---

metaflow/plugins/pypi/conda_environment.py

fixes `argo-workflows create` not working with conda/pypi environments

fix: argo daemon with conda environment

---

metaflow/metaflow_environment.py

fix: correctly quote endpoint_url option in s3 bootstrap command

---

metaflow/plugins/pypi/bootstrap.py

This is needed for environments where there are no containers (eg: SLURM)
This avoids two different processes writing to a shared folder in parallel, thus avoiding contention issues due to which data can be corrupted..

separate micromamba pkg dirs

---

metaflow/metaflow_current.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/aws/batch/batch_client.py
metaflow/plugins/kubernetes/kubernetes.py
metaflow/plugins/parallel_decorator.py

- The control task's ID is not available at runtime when we are executing task-pre-step
- This maybe required for many downstream decorators that need this ID so that It can derive the control task's pathspec.
- Alters all execution/orchestration decorators to account for an environment variable that allows setting `control_task_id` inside the `Parallel` namedtuple

[current.parallel] add `control_task_id` attribute

---

metaflow/runner/deployer.py
metaflow/runner/metaflow_runner.py
metaflow/runner/utils.py

This avoids waiting for a long time after a process crashes when using the Runner or Deployer

Stop waiting for the status file when the process finishes

---

metaflow/__init__.py
metaflow/cmd/main_cli.py
metaflow/extension_support/__init__.py
metaflow/flowspec.py
metaflow/metadata/metadata.py
metaflow/metaflow_config.py
metaflow/metaflow_environment.py
metaflow/metaflow_version.py

This adds information to the system tags about the metaflow extensions that are installed. This makes it easier to reproduce the exact same environment. Information about whether the package information is complete or not is also included.
This PR also fixes some issues with extension loading and allows extension information to be gathered in a programatic fashion thereby enabling the discovery of extensions.

Add installed_extensions information

---

metaflow/plugins/argo/argo_workflows.py

when running flows with project branches, the Argo Workflows heartbeat fails to register the run correctly. This happens in cases where the heartbeat daemon registers the run when the start step has not yet started.
closes #2029

fix: argo workflows daemon run register can fail with project branches

---

metaflow/plugins/kubernetes/kube_utils.py
metaflow/plugins/kubernetes/kubernetes_cli.py
metaflow/plugins/kubernetes/kubernetes_client.py

supersedes #1998 as the first attempt, as this approach is backwards compatible.
closes #1631 
**caveat**
this approach iterates through all active pods in a namespace indiscriminately (with a limit of `1000` per request), only filtering on the client side for relevant ones. As a result, in deployments with enormous amounts of active pods, the operation can take quite long.

feature: backwards compatible Kubernetes list and kill

---

metaflow/plugins/pypi/conda_decorator.py

attach `conda` decorator to steps in the `conda_base` decorator when using it. 
This solves an issue where a virtual environment implemented in an extension does not append `conda` as part of environment decospecs, but still needs to know whether a step needs to execute on conda due to the flow decorator.
`decorators._attach_decorators` is a no-op for existing conda decorators on a step so this should not have adverse effects.

fix: attach conda decorator in conda_base flow_init

---

metaflow/__init__.py
metaflow/client/core.py
metaflow/cmd/main_cli.py
metaflow/extension_support/__init__.py
metaflow/flowspec.py
metaflow/info_file.py
metaflow/metaflow_config.py
metaflow/metaflow_environment.py
metaflow/metaflow_version.py
metaflow/package.py
metaflow/plugins/pypi/conda_decorator.py

Favors reading the INFO file if present to be able to have the most accurate version of Metaflow when executing remotely (especially in the presence of extensions).
Also limit reading the INFO file to once per process (as opposed to possibly twice).
Finally, gets the version of the source of Metaflow (and not the current directory)

Modify getting Metaflow version

---

metaflow/cli.py
metaflow/runner/deployer.py
metaflow/runner/metaflow_runner.py
metaflow/runner/subprocess_manager.py
metaflow/runner/utils.py

This PR is inspired by a few ideas from
- https://github.com/Netflix/metaflow/pull/2039 (fix for SIGINT handling)
- https://github.com/Netflix/metaflow/pull/2033 (`poll()` not available for the `Process` object created async)
It also comes with:
- storing json contents in runner attribute file
- setting status as "timeout" if it occurs

runner fixes and enhancements

---

metaflow/runner/deployer.py

The `_enrich_object` method currently sets attributes at a class level. 
- If we have multiple instances of a `TriggeredRun` or `DeployedFlow` in a script/notebook, then using `_enrich_object` to add/set an attribute like `url` to a `TriggeredRun` instance, would modify it for all the instances. 
- We might want a behavior where these attributes are set at an instance level, just like the methods are being set currently.

Modify `_enrich_object` deployer method to set instance attributes

---

metaflow/plugins/kubernetes/kubernetes_client.py

add message to kubernetes kill for case where no pods are found

fix: add messaging to kubernetes kill

---

metaflow/plugins/argo/argo_workflows.py

due to changes in parameter quoting in the CLI, passing jsontype parameter default values has stopped working. Attempt to mend the issue with this PR
parameter default testing needs to cover:
- basic `argo-workflows trigger --param_name value` functionality
- cronworkflow parameter defaults with `@schedule`
- Argo Events payload parameter mapping

fix: Argo Workflows JSONType parameters with default values sometimes not working

---

metaflow/plugins/pypi/micromamba.py

add specific error messages with instructions for conda virtual packages
example output:
```
Micromamba ran into an error while setting up environment:
nothing provides __glibc >=2.17,<3.0.a0 needed by pyside6-6.7.2-py310heb5a38e_0
Please set the environment variable CONDA_OVERRIDE_GLIBC to a specific version
```

feature: conda virtual packages error messages

---

metaflow/plugins/kubernetes/kubernetes_client.py

issue with _kill executor scope leads to the no-pods message even when pods were found.

fix: kubernetes kill no-pods messaging

---

metaflow/plugins/argo/argo_workflows_cli.py

remove reliance on workflow_name in argo workflows `validate_run_id` as workflow names can be truncated (even more so in the future)

fix: argo validate_run_id with truncated workflow names

---

metaflow/plugins/argo/argo_workflows.py

The slack ui_link needs a slight bug fix. The url is missing a slash.
Why This Matters:
User Experience:
- Incorrect URLs in notifications can frustrate users and hinder workflow.
- Ensuring correct URL formatting improves reliability.
Code Maintainability:
- Proper handling of strings and URLs prevents bugs.
- Consistent practices make the code easier to understand and maintain.
Thanks y'all, and great project here!

Fix slack ui_link

---

metaflow/plugins/argo/argo_workflows.py

adds service account to argo exit hook, as the container relies on pulling metaflow/codepackage content from the datastore before running its script.

fix: add service account to argo exit hook

---

metaflow/decorators.py
metaflow/plugins/aws/batch/batch_decorator.py
metaflow/plugins/kubernetes/kubernetes_decorator.py
metaflow/plugins/pypi/conda_environment.py

The problem is that as new execution environment decorators are being introduced, we need to constantly keep adding these to the list of supported decorators for `@pypi/@conda`.
Proposal is to instead have two flags on step decorators that keep track whether
- decorator is a conda supported execution environment
- what the target platform of said environment is
in the case of the target platform, a decorator could then implement this as a dynamic property if it can be inferred during env resolve time on a per step basis. (f.ex. for the kubernetes decorator through label selectors for `arch`)

feature: enable extending pypi/conda execution decorator support

---

metaflow/plugins/cards/card_decorator.py
metaflow/plugins/kubernetes/kubernetes_decorator.py
metaflow/plugins/parallel_decorator.py

In Kubernetes, jobsets ensure that all jobs within the set are scheduled together. However, while they may be scheduled concurrently, the order in which they start executing is not guaranteed. This can cause issues if a worker job starts before the control job, as the worker may fail to resolve the control job’s hostname, leading to a crash.
This update introduces a configurable `hostname_resolution_timeout`, allowing worker jobs to wait for a defined period to resolve the control job's hostname before terminating. This adds a layer of resilience, preventing crashes caused by timing issues between job start times.
One thing to note here is that if the control job finishes before the worker job starts, the worker will still wait for the `hostname_resolution_timeout`. Given that many …

[kubernetes][parallel] hostname resolution timeout

---

metaflow/plugins/azure/azure_tail.py
metaflow/plugins/gcp/gs_tail.py
metaflow/plugins/kubernetes/kubernetes.py

Fixes an issue where log tailing stops working after a point on GCP, resulting in missing log output on the terminal.
The cause is with the behaviour of `google.cloud.storage` blob client, where consecutive requests with identical attributes on a single instance will not yield different responses, even if the underlying blob has advanced.
Example flow to reproduce missing log lines on GCP:
```python
from time import sleep
from metaflow import (
FlowSpec,
step,
kubernetes,
)
import os
class MinimalKubeGCPLogExample(FlowSpec):
@kubernetes
@step
print("BUFFERED: %s" % os.getenv("PYTHONBUFFERED"))
print("first log line so as not to have an empty file")
for i in range(10):
print(f"{i}\r", end="")
sleep(1)
print("\r\n")
print("after progress lines")
@step …
```

fix: missing loglines from tailing logs with GCP

---

metaflow/cli.py
metaflow/client/core.py
metaflow/metadata/metadata.py
metaflow/plugins/argo/argo_workflows_cli.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/plugins/tag_cli.py
metaflow/runner/metaflow_runner.py
metaflow/task.py

This also makes metadata more local to the object than a global concept all the time. This should allow objects across metadata services to work together.

Set metadata properly in runner

---

metaflow/task.py

if a flow contains unpicklable artifacts, the task status for such a step is recorded as `successful` even though pickling fails and leads to a non-zero exit for the task.
example:
```python
from metaflow import FlowSpec, step, kubernetes
class DemoFlow(FlowSpec):
@kubernetes
@step
self.x = open("hello.txt", "w")
@step
def end(self):
pass
DemoFlow()
```

fix: task status issue with unpicklable artifacts

---

metaflow/cli.py
metaflow/runtime.py
metaflow/system/system_logger.py
metaflow/system/system_monitor.py
metaflow/task.py

This PR removes the notion of a separate global context from `system_monitor` and `system_logger`. User's can now implement their event loggers and monitors to make use of the current singleton instead. 
Additionally, it adds the `graph_info` object to the current singleton, but it is not directly exposed to the end user.

Refactor system event logger and monitor, add new metrics

---

.github/workflows/test.yml

R test failure is blocking release pipeline. The tests passed with 4.4.1 and failed for 4.4.2, pin R version as a temp fix to unblock tests

ping r version to 4.4.1 to fix test

---

metaflow/plugins/env_escape/__init__.py

A small update to the escape hatch stubs. In notebooks, `''` is not necessarily the first element of `sys.path`, so when updating the `sys.path` when the escape hatch client is launched from CWD, we look at all elements of `sys.path` instead of just the first element like previously.

Update escape hatch sys path when used in jupyter notebook

---

metaflow/cli.py

- Ensuring parity with the `resume` command.

[runtime] run heartbeats for local runtime's `run` command

---

metaflow/parameters.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/events_decorator.py

Revert "Deploy time triggers"

---

metaflow/plugins/argo/argo_workflows_deployer_objects.py
metaflow/plugins/aws/step_functions/step_functions_deployer_objects.py
metaflow/runner/deployer_impl.py
metaflow/runner/metaflow_runner.py
metaflow/runner/subprocess_manager.py
metaflow/runner/utils.py

Follow-up to https://github.com/Netflix/metaflow/pull/2053
Added an async implementation of Runner's signal handling, as discussed here https://github.com/Netflix/metaflow/pull/2053#discussion_r1771641866.
Added an async implementation of Runner's `__get_executing_run`, which is used in `async_run` and `async_resume`, the current implementation relies on `time.sleep`, which blocks other coroutines from running (modified code from my previous PR https://github.com/Netflix/metaflow/pull/2033).

Async runner improvements

---

metaflow/plugins/datatools/s3/s3.py

S3 paths with url fragments do not work with the Metaflow S3 client, but do work with boto3 directly. The cause is that any key we pass to S3 methods goes through `urlparse`, of which we only use `netloc` and `path`. Fragments get parsed into their own key in the ParseResult.

fix: S3 paths with fragments not working

---

metaflow/multicore_utils.py

This change adds generic typing into the functions from multicore_utils.py. This allows for better type checking.

Add generic typing to multicore_utils.py

---

metaflow/plugins/argo/argo_workflows.py

missing dict conversion for recent additions of `V1Container` objects which leads to non json-serializable payloads

fix: argo workflows --only-json

---

metaflow/plugins/parallel_decorator.py
metaflow/runtime.py
test/core/graphs/parallel.json
test/core/tests/resume_ubf_basic_foreach.py
test/core/tests/resume_ubf_foreach_join.py

`@parallel` uses the control task as a mapper task. This was not a situation the resume functionality for UBF handled well.
In the process, also cleared up some other bugs that could have cropped up later.
This should replace #2159.

Fix issue with resume combined with `@parallel`

---

metaflow/cli.py
metaflow/cli_components/run_cmds.py
metaflow/cli_components/step_cmd.py
metaflow/decorators.py
metaflow/plugins/airflow/airflow_cli.py
metaflow/plugins/argo/argo_workflows_cli.py
metaflow/plugins/aws/step_functions/step_functions_cli.py
metaflow/plugins/pypi/pypi_decorator.py

In some cases, specifically when using argo/airflow/sfn, the decorator's init function could be called twice which caused issues with the conda/pypi decorator.

Fix case where the decorator's init function could be called twice.

---

metaflow/plugins/argo/argo_workflows_deployer_objects.py
metaflow/plugins/aws/step_functions/step_functions_deployer_objects.py
metaflow/runner/deployer.py
metaflow/runner/deployer_impl.py
metaflow/runner/metaflow_runner.py
metaflow/runner/nbdeploy.py
metaflow/runner/nbrun.py
metaflow/runner/subprocess_manager.py
metaflow/runner/utils.py

In cases where we need to read from a file (for the result of run_command), the current code used to make it sequential (so the timeout was actually never triggered).
This started causing problems on MacOS when writing large amounts of data (8KB FIFO)

Fix issue where run_command blocks when it shouldn't

---

metaflow/plugins/pypi/conda_decorator.py
metaflow/plugins/pypi/pypi_decorator.py

base Decorator class now exposes `_user_defined_attributes` as a set. This differs in how it is used in conda/pypi decorators, and for the current pypi implementation, using `@pypi_base` leads to the set being used in dict splatting, resulting in an error.
Streamlining the usage in this PR to be in line with what the base class provides.
TODO:

fix: conda/pypi usage of _user_defined_attributes

---

metaflow/plugins/pypi/conda_decorator.py
metaflow/plugins/pypi/pypi_decorator.py
test/unit/test_conda_decorator.py
test/unit/test_pypi_decorator.py

add unit tests for conda/pypi decorator `is_attribute_user_defined` to guarantee proper functionality for extensions.
fix for user attribute values detection to both conda/pypi decorators

fix: conda/pypi user-defined attributes tracking

---

metaflow/runner/utils.py

context:
consider the flow at `f.py`
```py
from metaflow import FlowSpec, kubernetes, step, current, project, Flow
import os, time
class HelloFlow(FlowSpec):
@step
x.foo()
@step
def end(self):
print('value is', self.model)
if __name__ == '__main__':
HelloFlow()
```
and consider using it with:
```py
from metaflow import Runner
with Runner('./f.py').run() as running:
print('done')
```
the runner gets stuck after merging of #2169
if we try the following, it exits when the timeout passes...
```py
from metaflow import Runner
with Runner('./f.py', file_read_timeout=10).run() as running:
print('done')
```
since the default is 3600 secs, we should exit early..

fail early without needing to reduce file_read_timeout

---

metaflow/plugins/aws/secrets_manager/aws_secrets_manager_secrets_provider.py

Updated the docstring to reflect the correct option name json instead of the incorrect parse_secret_string_as_jso
If the secret contains a string payload ("SecretString"):
- if the `json` option is True (default):
{SecretString} will be parsed as a JSON. If successfully parsed, AND the JSON contains a
top-level object, each entry K/V in the object will also be converted to an entry in the result. V will
always be casted to a string (if not already a string).
- If `json` option is False:
{SecretString} will be returned as a single entry in the result, with the key being the secret_id.n.

refactor: rename parse_secret_string_as_json option to json for clarity

---

metaflow/runner/click_api.py

Context:
The `cwd` argument of the Runner is for selecting the directory under which the `subprocess` executes in..
But, it doesn't play a role in loading of the flow file itself -- which is the first step of the lower level API to generate the command that will be executed via `subprocess`..
aka loading of file --> generate command --> run via subprocess (`cwd` is only relevant here)
Thus, in the directory structure like this:
```
├── pipelines/
│   ├── training.py
│   └── common.py
└── tests/
└── test_sample.py
```
if `training.py` has `from common import packages`
and `test_sample.py` uses the Runner API as follows:
```
with Runner("pipelines/training.py", environment="conda").run() as running:
return running.run.data
```
the following issue is encountered:
```
>   from common import …
```

include flowdir in syspath while loading file in Runner API

---

metaflow/plugins/pypi/bootstrap.py
metaflow/plugins/pypi/micromamba.py
metaflow/plugins/pypi/utils.py

add support for downloading micromamba from high-throughput mirror

feature: micromamba download from mirror

---

metaflow/metadata_provider/heartbeat.py

- Ensure better error handling so that any server related flakiness can be handled without crashing the heartbeat thread.
- If the heartbeat thread crashes because of any server issues / DNS issues / Intermittent server flakiness, it will kill the heartbeat thread causing the UI to mark the run as failed. 
- This change ensures that we don't crash the thread an makes it exponentially backoff calling the server.

[heartbeats] Better error handling

---

metaflow/extension_support/plugins.py
metaflow/plugins/__init__.py
metaflow/runner/metaflow_runner.py

This allows extensions to add classes with associated methods like Runner("myflow.py", ...).cmd().subcommand()
As an example:
```
class RunnerCLI(object):
name = "environment"
def __init__(self, runner: "metaflow.Runner"):
"""
Environment command for the flow. Requires the conda environment.
"""
self.runner = runner
def resolve(
self,
steps_to_resolve: Optional[List[str]] = None,
arch: Optional[Union[str, List[str]]] = None,
alias: Optional[List[str]] = None,
force: bool = False,
dry_run: bool = False,
timeout: int = 1200,
) -> Dict[str, Dict[str, ResolvedEnvironment]]:
```
Would add a "environment" command which takes no argument and add the `resolve` subcommand.

Allow additional commands to be injected directly on the Runner()

---

metaflow/plugins/pypi/micromamba.py

Some Micromamba versions do not handle version strings with extra double-equals anymore (e.g. `==>=1.0.0`) so we clean up

fix: cleanup version strings for micromamba

---

metaflow/cli.py
metaflow/cli_components/run_cmds.py
metaflow/cli_components/step_cmd.py

Rebased earlier PR. Supersedes #1857 but keeping both open for easier comparison that nothing was lost in the rebase
Original: This was not used anywhere and step is an internal command. Also added clarifying comments around attaching decospecs

fix: remove step level decospecs

---

metaflow/decorators.py
metaflow/parameters.py
metaflow/plugins/events_decorator.py
metaflow/plugins/project_decorator.py
metaflow/user_configs/config_parameters.py

This would allow for a more flexible use of configs as you can now provide those options directly from a config file.
This impacts the only two decorators that have this: project and trigger_on_finish

Allow TL flow-decorator options to be provided as part of the decorator

---

metaflow/plugins/cards/card_decorator.py

- Ensures configs behave consistently with cards.
Testing script to see it works : 
```python
from metaflow import FlowSpec, step, card, current, Config
from metaflow.cards import ProgressBar
def git_info(args=None):
from subprocess import check_output, CalledProcessError
info = {
"commit": ["git", "rev-parse", "HEAD"],
"branch": ["git", "rev-parse", "--abbrev-ref", "HEAD"],
"message": ["git", "log", "-1", "--pretty=%B"],
"remote": ["git", "config", "--get", "remote.origin.url"],
}
cfg = {}
try:
for key, cmd in info.items():
cfg[key] = check_output(cmd, text=True).strip()
except CalledProcessError as e:
cfg["error"] = f"Git command failed: {e}"
return cfg
class PythonCodeDemoFlow(FlowSpec):
git_info = Config("git_info", default_value="", parser=git_info)
@card
@card(type="blank", …
```

[cards] Fix config issue permanently.

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/events_decorator.py

There is a bug specifying `project_branch` in the `@trigger_on_finish` decorators flow dictionary is ignored completely, leading to listening on events that will never be broadcast.
This PR also adds validation so we don't deploy with event names containing partial project info.
Example:
This flow incorrectly listens to the event `sa_test_project.ProjectEventsTestFlow`
```python
@trigger_on_finish(
flow={"name": "ProjectEventsTestFlow", "project": "sa_test_project", "project_branch": "user.saikonen"}
)
class TriggerOnProjectFinish2(FlowSpec):
pass
```

fix: Argo events project bug

---

metaflow/decorators.py

If you used MutableFlow to inject a flow level decorator that has TL options, Metaflow would crash.

Fix an issue with using MutableFlow

---

metaflow/parameters.py
metaflow/runner/click_api.py
metaflow/user_configs/config_options.py
metaflow/user_configs/config_parameters.py

If a config was None (ie: no default, default value and not required), in certain circumstances, Metaflow would crash.
Fixes #2191

Fix an issue with configs that were None

---

metaflow/flowspec.py

If a flow didn't have a MutableFlow decorator but had MutableStep decorators, the decorators were not processed.

Fix an issue where processing MutableStep decos was skipped

---

metaflow/plugins/kubernetes/kubernetes_decorator.py

fixes edge case where `@kubernetes` decorator fails to execute `task_pre_step` due to another decorator raising exceptions. guards against the missing metadata during `task_finished`
This still leaves the issue where kubernetes `task_pre_step` not executing will lead to some missing metadata as well.
relates to #2231 for a thorough fix.

fix: guard against missing metadata in Kubernetes decorator

---

metaflow/plugins/pypi/micromamba.py

deferring micromamba binary installation in the last release (`2.13.8`) caused two issues
- when micromamba is not installed, there is a race condition due to environments being solved in parallel which can kick up multiple installs at a time
- the property was not returning the path to the binary after installation, leading to first calls failing.

fix: issue with deferred micromamba installation

---

metaflow/metaflow_config.py
metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_cli.py

adds basic support for incident.io alerts through Argo Workflows

feature: basic support for incident.io in Argo Workflows

---

metaflow/plugins/argo/argo_workflows_cli.py
metaflow/runner/click_api.py

last release introduced an issue that broke the argo workflows/step functions deployer implementation. The cause is https://github.com/Netflix/metaflow/pull/2234/files#diff-5b4ba4c231c3ab3a8e1df579662e664605edf1b903b2299b0d75a7613ffca945R530-R535 as the Argo deployer relies on a hidden Click option to pass values.
minimal repro example:
```python
from metaflow import Deployer
if __name__=="__main__":
deployer = Deployer(flow_file="HelloFlow.py").argo_workflows()
deployed_flow = deployer.create()
```
will result in an error
```
ValueError: Unknown argument: 'deployer_attribute_file', possible args are: authorize, generate_new_token, given_token, tags, user_namespace, only_json, max_workers, workflow_timeout, workflow_priority, auto_emit_argo_events, notify_on_error, notify_on_success, …
```

fix: Deployer issue

---

metaflow/version.py

2.13.10 had breaking issues with deployer/runner
bumping minor version due to the changes to default Pickle protocol version.

release: 2.14.0

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_cli.py

fixes issues with argo workflows nontifications that were uncovered by the recent incident.io feature.
- change slack and pagerduty CLI option defaults to `None` instead of empty string
- make sure that unrelated notification templates are not appended to the workflow template. Previously f.ex. slack notification templates were appended even when only configuring pagerduty.
- adds incident.io to the notification annotations

fix: Argo notifications issues

---

metaflow/plugins/aws/batch/batch_cli.py
metaflow/plugins/aws/batch/batch_decorator.py

👋 this is my first time here, excited to be contributing to the project
I implemented this based on  https://github.com/Netflix/metaflow/issues/2214 and https://github.com/Netflix/metaflow/pull/2207. Let me know if it looks ok and I can add tests.

feat: update metadata on ec2 spot termination for batch

---

metaflow/plugins/kubernetes/kubernetes_jobsets.py

- Local scheduler was deleting succesfully completed jobsets. We avoid this now by ensuring that jobsets are killed or deleted when they are not running or waiting (in suspended state).

[jobsets] Fix bug in jobset atexit handler

---

metaflow/cmd/develop/stub_generator.py

If we have a decorator like `@my_deco` which does not have any parameters section in the docstring, then the generated stubs are wrong since it adds an empty `Parameters` section like the one shown below:
```
@typing.overload
def my_deco(f: typing.Callable[[FlowSpecDerived, StepFlag], None]) -> typing.Callable[[FlowSpecDerived, StepFlag], None]:
"""
My function docstring
Parameters
----------
"""
```
This causes issues when rendering the docs using `mkdocs`.

Fix issue in stubs where step decorators dont have any parameters

---

.github/workflows/full-stack-test.yml

uses the newly introduced `metaflow-dev` to spin up a complete stack for end-to-end testing inside GHA

feature: Metaflow end-to-end testing GHA

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_cli.py

switching the incident.io notification mechanism from directly creating incidents to instead creating alerts.
alerts offer a nicer flow and more customization on incident.io side. the setup is also less of a headache when deploying a flow, as users only need to create a http source endpoint for alerts, and provide the api key & source config id to Metaflow
accompanying docs changes: https://github.com/Netflix/metaflow-docs/pull/145

feature: replace incident.io incidents with alerts for the integration.

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_deployer_objects.py

example:
```
number = Parameter(
'input-number',
default=3,
help="don't input alphabets"
)
```
fixes https://github.com/Netflix/metaflow/issues/2349

fix python names and help params in DeployedFlow from_deployment

---

metaflow/plugins/argo/argo_workflows.py

fixes #2273
One drawback of this fix is that when triggering flows through Argo UI, the JSONType parameters values will have to now have outermost quotes, essentially being string-serialized json.

fix: json parameters argo workflows

---

devtools/Makefile

The dev stack's `aws_config` currently includes config (endpoint URL) and the credentials as well, and setting the `AWS_CONFIG_FILE` env var to point to that file, which works fine IF the user doesn't have a credentials file -- as per the related AWS docs at https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html?shortFooter=true#cli-configure-files-where:
> You can keep all of your profile settings in a single file as the AWS CLI can read credentials from the config file. If there are credentials in both files for a profile sharing the same name, the keys in the credentials file take precedence. We suggest keeping credentials in the credentials files.
This PR resets the credentials file reference by setting `AWS_SHARED_CREDENTIALS_FILE` to blank.
More details at …

reset AWS_SHARED_CREDENTIALS_FILE as AWS_CONFIG_FILE includes creds

---

.github/workflows/test.yml
metaflow/cli.py

When not running run/resume, default decospecs (either set by the user or an extension) where not attached. Specifically this resulted in issues when running through the scheduler.
This broken behavior was introduced in #2097.

Fix an issue where default decospecs were not applied

---

metaflow/plugins/datatools/s3/s3.py
metaflow/plugins/datatools/s3/s3op.py

Running out of disk space should be treated as a fatal error. It is currently treated as a transient error, leading to retries which never succeed. The task eventually dies after all the retries are exhausted.
This change makes `ENOSPC` a fatal error and we exit immediately.

Terminate early on ENOSPC

---

metaflow/includefile.py

The url is causing one user to hit the 8192 limit on SFN, so removing it.
https://netflix.slack.com/archives/C02116BBNTU/p1746004551121269

Remove url from payload

---

metaflow/plugins/datastores/gs_storage.py
metaflow/plugins/pypi/conda_environment.py

GS datastore uploads time out with large files due to default timeout being 60 seconds and not accounting for any activity in the connection. This PR bumps the timeout value to match that of the Azure storage implementation

fix: bump GS datastore save_bytes timeout

---

metaflow/metaflow_config.py
metaflow/plugins/pypi/conda_environment.py
metaflow/plugins/pypi/micromamba.py
metaflow/plugins/pypi/pip.py

enables debugging the Conda/PyPI environment processes with the `METAFLOW_DEBUG_CONDA=1` flag
stacked on top of #2399 for easier testing.

feature: add debug logging to conda_environment, micromamba and pypi

---

metaflow/plugins/datatools/s3/s3op.py

Setting default params doesn't play nicely with custom s3 providers. See original [thread](https://netflix.slack.com/archives/C02116BBNTU/p1747150548481859?thread_ts=1746546232.063489&cid=C02116BBNTU).
Also make `InvalidAccessKeyId` a fatal error. Currently:
```
[WARNING] S3 datastore operation list_prefix failed (An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.). Retrying 2 more times..
```

[S3] Revert default params in s3op.py

---

metaflow/plugins/uv/uv_environment.py

`uv run python` does syncing to the environment unless specifically instructed not to. this can lead to unnecessarily downloading/installing dependencies that were skipped during bootstrapping

fix: skip metaflow dependencies in uv-environment

---

metaflow/util.py

This small PR resolves the regex library warnings showing in Python3.11:
```python
DeprecationWarning: 'count' is passed as positional argument
```

Resolve regex calls warnings

---

metaflow/_vendor/click/core.py
metaflow/decorators.py
metaflow/metaflow_config.py
metaflow/parameters.py
metaflow/runner/click_api.py
metaflow/runner/deployer_impl.py
metaflow/runner/metaflow_runner.py
metaflow/runner/subprocess_manager.py
metaflow/runner/utils.py
metaflow/user_configs/config_options.py
metaflow/user_configs/config_parameters.py
test/test_config/config_corner_cases.py
test/unit/test_config_value.py

Now allows:
@environment(vars=config_expr("..."))
- This was broken since vars was a ConfigValue and not an updatable dictionary
@project(name=config_expr("get_my_name(cfg)"))
- This was broken because when evaluating the config_expr, we did not consider the globals at the point of call but instead inside the file defining config_expr.
Tests are deployed internally.

Extend the use of config_expr

---

metaflow/cli.py
metaflow/cli_components/run_cmds.py
metaflow/flowspec.py
metaflow/user_configs/config_decorators.py
metaflow/user_configs/config_options.py

- in some cases (if you called TWO commands like create and trigger) with a Runner/Deployer on the same flow, the flow/step mutators would be applied *twice* which could lead to weird errors (duplicate decorators)
- using a None default for configs failed (#2449)

Two fixes: runner/deployer with configs and None config

---

metaflow/cli.py
metaflow/plugins/pypi/conda_environment.py
metaflow/plugins/pypi/micromamba.py

adds a top-level option to toggle force-rebuilding the environment
```
python HelloConda.py --environment conda --force-rebuild-environment run
```
the introduction of the new option is not mandatory. we could simply proceed with an internal envvar to enable the functionality for now.

feature: alternate approach to environment force-rebuild

---

metaflow/plugins/aws/aws_utils.py

There is an error when trying to retrieve the IMDSv2 token because the header value is `int`. This causes all the requests to fall back to IMDSv1.

Fix IMDSv2 Error

---

metaflow/plugins/uv/bootstrap.py

`read_info_file` was relocated in the recent release. fix import in uv bootstrap

fix: uv bootstrapping

---

metaflow/plugins/argo/exit_hooks.py

fixes a regression with default notifications (slack/pagerduty/incident.io) with argo workflows that was caused by doublequotes in the http post body making notification messages not get processed.

fix: regression with default notifications on argo workflows

---

metaflow/decorators.py

The packaging PR #2463 introduced the `extract_args_kwargs_from_decorator_spec` to parse the decospecs added from the command line. This function has a subtle bug where it returns from the for loop instead of the end of the function.

[bug fix] fix subtle bug from netflix/metaflow#2463

---

metaflow/plugins/kubernetes/kubernetes_decorator.py

This is a very minor fix - but it confused me for a while, so for the next person poking at the code, this might be a good to sort out. The format of the tolerations is a dict with key and value strings. It is listed correctly in a comment further down in the codebase but incorrectly in the typehint.

Fixes tolerations typehint

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/argo_workflows_cli.py

handle old and new name length issues in the remaining commands: `terminate/suspend/unsuspend/delete/trigger`

fix: argo namelength issue fixes for remaining commands

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/kubernetes/kubernetes_jobsets.py

> Back story behind how this PR came to be ?
When we introduced JobSets into Argo Workflows, we had to implement a few "work-arounds" (hacks) in the JobSet manifest construction. One major hack we **HAD to implement** was replacing the `inputs.parameters.workerCount` in the JobSet manifest given to the Argo Workflow Template with an un-quoted templating string. The templating string looks like:`{{=asInt(inputs.parameters.workerCount)}}`. This templating string is quoted when we dump the manifest to a dictionary BUT having it quoted would mean the parameter gets casted as a string in the JobSet Manifest and jobset controller will reject that resource creation.
Argo on the other hand accepts storing the "malformed" manifest when we submit the workflow template and trigger it via the k8s …

[argo] Fix eventing for `@parallel` based workflow

---

metaflow/version.py

Minor versio bump due to breaking changes in argo-workflows name lengths

release: 2.17.0

---

metaflow/runner/deployer_impl.py

Make `to_reload` a property that can be overwritten by other implementations like `maestro` etc. This is because, sometimes we need to reload extension specific modules.

Fix bug in deployer reload logic

---

metaflow/plugins/argo/argo_workflows.py

Disable conditional steps inside foreaches on argo workflows for now due to issues in parameter value expressions.
The capabilities of Argos expression templating for parameter values do not work nicely with nested dag structures.

fix: disable conditionals inside foreach on argo

---

metaflow/plugins/argo/argo_workflows.py
metaflow/plugins/argo/conditional_input_paths.py

draft for now, as this approach had a bunch of issues caused by the "leftover" template literals in input-paths causing havoc to argo adjacent systems.

chore: re-enable conditionals in foreach on argo workflows

---

metaflow/client/core.py

The crux of the issue is that we save the bytes stream and TarFile modifies it when reading it and needs it to not be externally modified. This change ensures that there is no such modification.

Fix an issue where MetaflowCode.tarball would return a corrupted TarFile

---

README.md
metaflow/plugins/datatools/s3/s3.py
metaflow/plugins/datatools/s3/s3op.py

MetaflowExceptions were being treated as transient, leading to the `@timeout` decorator not terminating the flows.
Changed logic to treat all MetaflowExceptions as fatal.
Original thread: https://netflix.slack.com/archives/C02116BBNTU/p1758300976912159
Testing:
```
import os
import sys
from metaflow import FlowSpec, step, timeout
from metaflow.plugins.datatools.s3 import S3
S3ROOT = os.environ.get(
"METAFLOW_S3_TEST_ROOT",
"s3://netflix-dataoven-prod-users/rgruener/datatest/20220613/0/",
)
class HelloS3TimeoutFlow(FlowSpec):
"""
Flow that tests S3 timeout behavior by downloading a large file with a timeout.
"""
@timeout(seconds=5)  # 5-second timeout - impossible for 5GB file
@step
"""
Download a large file (5GB) with a 5-second timeout.
This should trigger …
```

[S3] Properly handle `TimeoutException`

---

devtools/Tiltfile

Starting August 28th, over two weeks, all existing container images, including older or versioned tags (e.g., 2.50.0, 10.6), will be migrated from the public catalog (docker.io/bitnami) to the "Bitnami Legacy" repository (docker.io/bitnamilegacy), where they will no longer receive updates.
See: https://hub.docker.com/r/bitnami/postgresql

Use legacy bitnami repo
